- Dashboard/app/js/lib/views/data/monitoring-data-table-view.js
* When 'Find' is clicked, we don't need to set the cursor (the 'since' parameter).
> [#1059] Don't set since cursor parameter

- Dashboard/app/js/lib/views/data/inspect-data-table-views.js
* by default, when you pick a day using the 
date picker, it has a time of 00:00. This means
that searching for the period 2014-1-1 to 2014-1-5
will actually search 2014-1-1 to 2014-1-4 inclusive.
As this is counter intuitive, we make the end date 
inclusive by adding 24 hours.
> [#325] Add a day to the end date search

- Dashboard/app/js/lib/controllers/data-controllers.js
- Dashboard/app/js/lib/views/data/cascade-resources-view.js
* Updating the status of a cascade resource is
triggered manually.
> [#1009] Trigger status update on edit

- Dashboard/app/js/lib/controllers/survey-controllers.js
- Dashboard/app/js/lib/views/views.js
* Fixes the issue where a folder was not shown in the list under `Data > Data Cleaning` tab when the data cleaning permission was assigned to a sub folder.
> [#943] Include ancestor paths for data cleaning permission

- GAE/src/org/waterforpeople/mapping/app/web/CurrentUserServlet.java
* When multiple roles are assigned to a single folder, ensure that all permissions are transmitted correctly to the dashboard
> [#1161] Merge permissions that are for the same path

- Dashboard/app/cljs/src/org/akvo/flow/dashboard/users/user_details.cljs
* GAE requires an empty body for DELETE.
> [#1156] Use url-request-format when revoking API keys

- GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
* Ensure that we pad with empty string when the answer is null
* Ensure that we don't split the answer into more parts than the level count
> [#1168] Fix cascading question padding issues in raw data reports

- Dashboard/app/js/lib/controllers/survey-controllers.js
* This was never implemented, the fix just fixes the UI
to be consistent with that.
* A proper implementation of copying across forms 
will need to be done later.
> [#1187] disable moving/copying across forms

- GAE/src/com/gallatinsystems/user/dao/UserAuthorizationDAO.java
- GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyInstanceRestService.java
- GAE/src/org/waterforpeople/mapping/app/web/rest/security/RequestUriVoter.java
* Fix the 403 error for `/rest/survey_instances?surveyedLocaleId=xxx` requests. User with permission should be able to make these requests
* Fix 403 error when the folder/survey is at root level and user does not have access to `All Folders and Surveys` permission 
* Filter `GET` request for `/rest/survey_instances` based on user authorisation
> [#1115] User authorisation for surveyed locales and survey instances

- GAE/src/com/gallatinsystems/survey/dao/SurveyUtils.java
- GAE/src/org/waterforpeople/mapping/app/web/DataProcessorRestServlet.java
- GAE/src/org/waterforpeople/mapping/app/web/dto/DataProcessorRequest.java
- GAE/src/org/waterforpeople/mapping/app/web/rest/QuestionGroupRestService.java
* If we are copying a single question group and the target option question
is in some previous group (i.e. not in the same group) we look up the dependant
question id via the original question (using the sourceQuestionId property).
> [#1217] Fix dependent question resolution

- scripts/data/src/org/akvo/gae/remoteapi/CorrectSurveyedLocale.java
- scripts/data/src/org/akvo/gae/remoteapi/DataUtils.java
* A RemoteAPI script to correct the surveyed locale for responses with the same surveyed locale identifier. Especially relevant for monitoring surveys.
* Added utility functions for batch saving and deleting against remote API
> [#1282] Correct surveyedLocaleIds for related survey instances

- Dashboard/app/js/templates/navReports/chart-reports.handlebars
#450
Wrap label text on the left of the chart to a max of 28 characters per line to avoid the text leaving the chart area
> [#450] wrap SVG label text to avoid text leaving the container

- GAE/src/com/gallatinsystems/survey/dao/SurveyUtils.java
- GAE/src/org/waterforpeople/mapping/app/web/DataProcessorRestServlet.java
- GAE/src/org/waterforpeople/mapping/app/web/rest/QuestionGroupRestService.java
* Use temporary `QuestionGroup` object when copying to avoid state sharing exception
* Remove logging line that throws *NPE* due to absence of a `keyId` in the temporary object
> [#1354] Fix survey copying regression

- Dashboard/app/js/lib/models/FLOWrest-adapter-v2-common.js
* We only consider the `since` property for SurveyInstance and SurveyedLocale entities for pagination
> [#1124] Ignore `since` meta property for all other request types

- Dashboard/app/js/lib/views/data/question-answer-view.js
* This is specifically for monitoring forms.  We use the response type value to render since the questions for monitoring forms are *not* yet loaded when browsing the monitoring tab and its therefore not possible to use the question.type property.
> [#1453] Render signature question type on monitoring tab

- Dashboard/app/js/lib/views/surveys/question-view.js
* The default options were saved but not associated with their respective questions because they had no questionId set
> [#828] Set questionId for options before creating default options

- GAE/war/WEB-INF/web.xml
Make sure `/devicetimerest` uses HTTP
> [#1564] Make sure /devicetimerest uses HTTP

- Dashboard/app/js/lib/views/data/question-answer-view.js
it seems that sometimes we have photo question answers which don't have PHOTO as their type - instead IMAGE. When this happens the logic for displaying lat/lon and parsing the JSON responses breaks down.
> [#1527] adding check for IMAGE type as well as PHOTO

- Dashboard/app/js/lib/router/router.js
- GAE/src/org/waterforpeople/mapping/app/gwt/client/survey/SurveyGroupDto.java
- GAE/src/org/waterforpeople/mapping/app/gwt/client/survey/SurveyService.java
- GAE/src/org/waterforpeople/mapping/app/gwt/server/survey/SurveyServiceImpl.java
- GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyGroupRestService.java
* Get rid of BeanUtils for copying properties
* Rearranged order of requests to dashboard. Cascade resources and metrics end points loaded after surveys
* Reduced `surveyList` to array of IDs instead of array of Survey entities
> [#987] Improve performance of loading dashboard

- Dashboard/app/js/lib/views/data/monitoring-data-table-view.js
- GAE/src/com/gallatinsystems/survey/dao/DataPointApprovalDAO.java
- GAE/src/org/waterforpeople/mapping/app/web/rest/DataPointApprovalRestService.java
The approval status for a data point was always reset to the first step in an approval group.  This fixes the issue.
We are now loading the approval status just after loading the data points.  This shows the correct status in which a data point is.
> [#1786] Data point approval status (connect #1786)

- Dashboard/app/js/lib/views/data/monitoring-data-table-view.js
- Dashboard/app/js/templates/navData/monitoring-data-row.handlebars
The data point status was not shown when a set of approvals was completed, making it impossible to review the comments on the different approval steps.
Fix includes displaying the last step when approvals have been completed as well as including the status of that last step.
> [#1785] Data point approval status on completion (connects #1785)

- Dashboard/app/js/lib/views/data/monitoring-data-table-view.js
The monitoring data tab is not loading data points because it encounters a null object error due to a wrongly returned property.  This fix ensures the correct property is returned.
> [#1880] Fix to return the next ApprovalStep entity not its `keyId` (connects #1880)

- Dashboard/app/js/lib/views/data/monitoring-data-table-view.js
For cases where an approval step is rejected, the data point status was still showing the following approval step as pending whereas it should show the last step along with the status as being rejected.
> [#1882] Show correct approval status for rejected data points (connects #1882)

- Dashboard/app/js/lib/controllers/data-controllers.js
- Dashboard/app/js/templates/navSurveys/project.handlebars
- GAE/src/locale/en.properties
- GAE/src/locale/ui-strings.properties
* When assigning a data approval to a survey, the dropdown already contained a selected approval.  This is now replaced with a prompt to select an approval.
* In addition, when creating an approval group, the default setting is to an `Ordered` approval group since this is the only type we are dealing with at the moment.
> [#1770] Data approval assignment dropdown (connect #1770)

- Dashboard/app/js/templates/application/footer-public.handlebars
- Dashboard/app/js/templates/application/footer.handlebars
- LICENSE.md
Copyright year span 2012-2016 would be outdated by the time of the release.
Changed to 2012-2017
> [1845]Update copyright headers to 2012-2017 for January release. (Connect #1845)

- Dashboard/app/dashboard.html
- GAE/src/org/waterforpeople/mapping/app/web/EnvServlet.java
> [#1732] do not include Google maps library unless when needed (connect #1732)

- Dashboard/app/js/lib/controllers/data-controllers.js
> Load metrics end point only when showStatisticsFeature flag is enabled (connect #1855)

- GAE/src/org/waterforpeople/mapping/app/gwt/server/survey/SurveyServiceImpl.java
A regression was introduced in this commit (3a70e36b0a50cc2aee620adfa22a51407dc60fcb) that removed the code to rebuild data point names when a survey is republished.
We reintroduce the datapoint name rebuilding code.
> Fix regression for datapoint name rebuild (connect #1934)

- Dashboard/app/js/templates/navMessages/nav-messages.handlebars
- GAE/src/locale/en.properties
- GAE/src/locale/ui-strings.properties
> [#1976] remove user column (connect #1976)

- GAE/src/org/waterforpeople/mapping/app/gwt/client/survey/SurveyGroupDto.java
- GAE/src/org/waterforpeople/mapping/app/web/SurveyRestServlet.java
- GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
- GAE/src/org/waterforpeople/mapping/dataexport/SurveySummaryExporter.java
- GAE/src/org/waterforpeople/mapping/dataexport/service/BulkDataServiceClient.java
This PR is part of the work that will go into data approval report generation.  In order to generate the reports, we need to know whether a particular `SurveyGroup` entity has been assigned the property `requireDataApproval == true`.  
Currently we have a utility method to retrieve an entire list of `SurveyGroup` entities, however, when generating a report we only need a single once, for the current report.  We therefore refactor our code to enable retrieving a single entity and remove some unneeded code as well.
We also use Jackson library for parsing the returned JSON responses.
> Enable retrieval of a single `SurveyGroup` entity as part of data approval report generation (connect #1666)

- Dashboard/app/js/lib/views/maps/map-views-common-public.js
- Dashboard/app/js/lib/views/maps/map-views-common.js
Mapbox maps were zooming so far out that there would be an overlap
Set minimum zoom level to 2 which fits the world map so user cannot zoom out any further
> Set minimum zoom for mapbox maps (connect #2001)

- GAE/src/com/gallatinsystems/survey/dao/DataPointApprovalDAO.java
- GAE/src/org/waterforpeople/mapping/app/web/SurveyInstanceServlet.java
- GAE/src/org/waterforpeople/mapping/app/web/dto/InstanceDataDto.java
- GAE/src/org/waterforpeople/mapping/app/web/dto/SurveyInstanceRequest.java
* We are retrieving the different elements required to build up reports in separate requests to the backends.  however, this creates too much unnecessary traffic and possible points of failure
* We combine the request for instance data into a single call.  This is the first half of the changeset.  In this part we refactor the `SurveyInstanceServlet` to support a single action `getInstanceData` that returns all the data corresponding to a single response.  For now we return the instance data and the approval status of the corresponding data point.  In a later PR we will use this request to populate the raw data report column
> Retrieve survey instance data and data approval status in combined request (connect #1666)

- Dashboard/app/js/lib/models/models.js
- GAE/src/com/gallatinsystems/survey/domain/Question.java
- GAE/src/org/waterforpeople/mapping/app/gwt/client/survey/QuestionDto.java
- GAE/src/org/waterforpeople/mapping/app/web/SurveyAssemblyServlet.java
- GAE/src/org/waterforpeople/mapping/app/web/SurveyRestServlet.java
- GAE/src/org/waterforpeople/mapping/dataexport/SurveySpreadsheetImporter.java
* The `isName` property was intended to be marked and used to generate validation rules for questions of type `QuestionType.NAME`. However, this question type is never used and therefore the validation rule is never generated in the survey definition.
* We remove the question type, its associated property and the code for generating the corresponding validation rule.
> Remove `NAME` question type and associated properties (connect #2053)

- GAE/src/com/gallatinsystems/survey/dao/QuestionDao.java
- GAE/src/org/waterforpeople/mapping/analytics/SurveyQuestionSummarizer.java
- GAE/src/org/waterforpeople/mapping/app/gwt/server/survey/SurveyServiceImpl.java
- GAE/src/org/waterforpeople/mapping/app/web/BootstrapGeneratorServlet.java
- GAE/src/org/waterforpeople/mapping/app/web/DataProcessorRestServlet.java
- GAE/src/org/waterforpeople/mapping/app/web/SurveyRestServlet.java
Questions are loaded by looping over question groups, making many datastore calls.
Fetch them in a bunch do the sorting ourselves.
> Issue/1442 optimise question loading (Connect #1442)

- GAE/src/com/gallatinsystems/survey/dao/QuestionOptionDao.java
- GAE/src/org/waterforpeople/mapping/app/web/rest/QuestionRestService.java
* Adding a QuestionOptionDao function to query for question options based on a list of questionIds provided.  The function also skips querying for the translation entities of QuestionOptions as these are not needed for a `GET /rest/questions?surveyId=` request.
> Ignore option translations (connect #1442)

- GAE/src/org/waterforpeople/mapping/app/web/rest/ActionRestService.java
* Avoid an NPE from occurring if the survey being copied is a non-monitoring one and therefore doesn't contain a registration form.
* Renaming some of the variables
> Fix NPE when copying non-monitoring surveys (connect #2074)

- GAE/src/com/gallatinsystems/survey/dao/QuestionDao.java
- GAE/src/org/waterforpeople/mapping/app/web/BootstrapGeneratorServlet.java
* When attempting to generate manual bootstrap loading file for forms not containing cascading questions, an error occurred as a result of a `null` result returned when querying for a list of cascading questions.  This error subsequently prevented the generation of a bootstrap file for that form
* When no cascading questions are found for a particular form, we return an empty collection of questions. 
* We also improve the logging of bootstrap errors in order to be able to identify the exception in logs
> Fix broken bootstrap file generation for forms without cascading questions (connect #2078)

- Dashboard/app/cljs/src/org/akvo/flow/dashboard/users/role_details.cljs
* The data approval permission was included in the list of permissions even on instances where this feature is not enabled.
* We filter out this permission from the list based on a setting from the flow environment variables `FLOW.Env.enableDataApproval`
> Hide data approval permission on users tab if not enabled (connect #2085)

- GAE/war/WEB-INF/rest-servlet.xml
* Calls to endpoints on the backend failing because of a missing or failed bean definitions.  This was caused by a bean definition for a non-existing class that caused the rest of the bean definitions to fail as well.
* Remove the bean definition for a non-existent class
> Remove non-existent class bean definition (connect #2022)

- GAE/war/WEB-INF/web.xml
* The configuration for api endpoints servlet is included in the web.xml.  However, since we restrict the access of this endpoint through the `<security-constraint>` configuration, the deployment fails.  GAE documentation advises that this endpoint is not to be restricted through the web.xml.  It should be done as described here https://cloud.google.com/endpoints/docs/frameworks/legacy/v1/java/add-authorization-backend
_Note: we are not using API endpoints so we do not need to follow these steps_
* We remove the configuration for restricted, authorized access of this endpoint in the web.xml
> Remove API endpoints servlet configuration (connect #2112)

- Dashboard/app/js/templates/navSurveys/question-view.handlebars
A user with view rights only could open a survey and click on the question text to enable question editing
A permissions check is now done before enabling clickable question text
> Disable clickable question text for users with view rights only (connect #2146)

- Dashboard/app/js/lib/router/router.js
- Dashboard/app/js/templates/navReports/reports-subnav.handlebars
Reports export is most used sub-feature of reports, but is on second, non-default tab.
Move it first and make it default.
> Issue/2151 change order reports subnav (Connect #2151)

- GAE/src/org/waterforpeople/mapping/dao/SurveyInstanceDAO.java
App des not send the displayname for a monitoring (non-registration) survey.
If missing, copy it from the old SurveyedLocale.
> [#1762]Copy SurveyedLocaleDisplay name from old SL if null. (Connect #1762)

- GAE/src/org/akvo/flow/servlet/config/AkvoFlowXmlWebApplicationContext.java
- GAE/src/org/akvo/flow/servlet/config/ProductionEnvironmentXmlWebApplicationContext.java
- GAE/war/WEB-INF/web.xml
* The spring framework performs XML validation on the beans definitions that affects performance of an application. 
* We disable the XML validation for production environments.  Given that this is risky for misconfigured beans, we correctly set the system property for development environments to be able to catch any validation issues.
> Disable xml validation in production environments (connect #2022)

- GAE/src/org/waterforpeople/mapping/app/web/EnvServlet.java
* In the PR https://github.com/akvo/akvo-flow/pull/2172/files the `appId` property was accidentally deleted.
* We reintroduce the property.
> Fix deleted `appId` property (connect #2153)

- GAE/war/WEB-INF/webapp-security.xml
* We were also filtering all static files through the security filter chain that checks a number of things that are not relevant to controlling access to these static files
* We bypass the security filter chain for static files
> Exclude static files from security filter chain (connect #2183)

- Dashboard/app/js/lib/router/router.js
* When loading the devices tab, the devices list, the device group list and additionally the survey assignments list are loaded.  Its not necessary to load this last list until a user actually selects the survey assignments tab.
* We only load the assignments list when a user clicks on the survey assignments tab
> Load survey assignments list only when tab is selected (connect #2035)

- GAE/src/org/waterforpeople/mapping/app/web/SurveyInstanceServlet.java
No displaynames shown for non-monitoring survey reports
Use survey of the surveyInstance if there is no creationSurveyId for surveyedLocale entity
> Issue/2232 displaynames for vanilla surveys (Connect #2232)

- Dashboard/app/js/lib/controllers/survey-controllers.js
- GAE/src/org/waterforpeople/mapping/app/web/EnvServlet.java
- GAE/war/Env.vm
* Caddisfly URL has been hardcoded but we would like this to be configurable to be able to overwrite the configuration for test files.
* Configure an environment variable for the caddisfly file URL
* Default URL is set if no property is present in the configuration file
> Set the caddisfly test file URL using environment variable (connect #2250)

- GAE/src/com/gallatinsystems/survey/dao/CaddisflyResourceDao.java
- GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
* Reports generation used the default hard-coded caddisfly tests file URL
* We use the properties from the appengine-web.xml file to configure the caddisfly tests file URL if its available.  If no property is present, we fall back on the default file.
> Add caddisfly test definitions file URL for report generation (connect #2250)

- GAE/src/com/gallatinsystems/framework/dao/BaseDAO.java
* Some items were ~randomly~ skipped when fetching surveyInstances and questionAnswers. Using `Math.round()` to determine the number of iterations to make meant the last IDs are skipped because we do one less iteration round that is required to complete them all.
* We use the ceiling function to ensure that ids in the `idsList` are processed when iterating over the list.
NA
> Fixed skipped items by list retrieval logic (connect #2252)

- Dashboard/app/js/lib/controllers/general-controllers-common.js
- Dashboard/app/js/lib/views/reports/export-reports-views.js
- Dashboard/app/js/templates/navReports/export-reports.handlebars
dropdown  for selecting language was confusing  to some users 
Remove the select language dropdown thus do away with translations in reports
> Remove translations in reports (connect #2286)

- Dashboard/app/css/main.scss
- Dashboard/app/js/templates/navDevices/assignment-edit-tab/assignment-edit.handlebars
The page where Assignments were edited had a heading 'Edit Assignments' and the button 'Go back to assignment list was on the left side of the page.
Removed the heading by removing its html line of code from the assignment-edit.handlebars file
Changed the position of the button from left to right by adding a css id 'float-right' to the html tag and adding the float-right style in the main.scss file where the float style is set to right.
> Improve assignments UI (#connect 2075)

- GAE/src/com/gallatinsystems/surveyal/domain/SurveyedLocale.java
- GAE/src/org/waterforpeople/mapping/app/web/RawDataRestServlet.java
* The data point location was not being updated on the map when data was changed via data cleaning
* When saving data from data cleaning, we check for any `GEO` question answers and use those to update the datapoint location.  Note: We do this only when updating registration forms responses for existing datapoints.
> Update the datapoint geolocation based on updated responses (connect #1839)

- GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
- GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
Before the PR (what is the issue or what needed to be done)
Data cleaning reports were hard to use.
The solution
Reorganise the repeatable question groups, putting their responses on separate sheets.
Also added headers for each group
Screenshots (if appropriate)
Test plan:
make a data cleaning report.
change a value.
import it back into Flow and check that only that value was changed.
make a raw data report with advanced setting "for use with external system" (setting the useQuestionId option, which outputs the "variable names" as column headings).
check that it still has the old format.
> [#2278]Remove unused parameters. (Connect #2278)

- Dashboard/app/js/templates/navReports/export-reports.handlebars
* Remove the option to include only last monitoring form submissions in the report
> Remove the last collected data option from the data cleaning report (connect #2339)

- Dashboard/app/js/lib/views/views.js
* The introduction of the `tagName` property in the controller class was causing the survey selector to crash when loading.
* We remove the unneeded tag.
> Remove unneeded div tag (connect #2353)

- Dashboard/app/js/templates/navReports/export-reports.handlebars
* There is HTML markup and some javascript that was intended for popping up a dialog when reports are requested.  However we will leave this part for a follow up issue as currently there is a dialog box that is already shown
* Remove the code
> Remove incomplete report generation dialog code (connect #2349)

- GAE/build.xml
Java 8 features would not compile for GAE
Exclude them
> [#2347]Exclude datatexport files from GAE build. (Connect #2347)

- Dashboard/app/js/templates/navData/cascade-resources.handlebars
Add level option under the Cascade tab appeared as clickable text. The issue required for this to be changed and make it look like a button so that it stands out.
Changed the CSS class of the <a> tag to an already existing class that had style specifications that could work: smallButton. This gave it the style of a button
> Changed Add level text design (Connect #2268)

- GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Localised report code was unused
Remove it
The removal is a little hard to test without a UI that lets you specify a locale, and we recently removed that, but the tester should verify that the reports still output the expected column headers and other labels (such as in the comprehensive stats).
> [#2309]Remove all report localisation code. (Connect #2309)

- Dashboard/app/js/lib/views/surveys/question-view.js
- Dashboard/app/js/templates/navSurveys/question-view.handlebars
When adding a question to a form, after selecting the question type, additional settings may be displayed in a grey text box. 
For question types with no additional settings e..g. video,date,signature,photo, a grey text box with "No additional settings for this type of question" is displayed. This was to be removed in this issue
Removed the {#if} clause displaying the message "No additional settings for this question type" from question-view.handlebars .
Added a function in question-view.js to identify question types with extra settings in the template.
Added a condition for extra settings to be displayed in question-view.handlebars: {{if view.hasExtraSettings}}, thus the div with extra settings is displayed unless the question type has no extra settings
> Remove no additional settings for questions with no extra settings (connect #2319)

- Dashboard/app/js/lib/controllers/survey-controllers.js
- Dashboard/app/js/lib/views/surveys/question-view.js
The Caddisfly test dropdown will remain in the screen even when the user selects another question type like free text , options when editing the question.
Caddisfly test dropdown does not show when you select another question type.
> Caddisfly dropdown remains in changed question testing(connect #1809)

- Dashboard/app/css/main.scss
- Dashboard/app/js/lib/views/data/monitoring-data-table-view.js
- Dashboard/app/js/templates/navData/monitoring-data.handlebars
When a user tried to find data points under the monitoring tab without specifying any survey, no result would be returned and there was no indication that no results were found
Added a function, noResults, in monitoring-data-table-view.js that searches for content and if none is found, returns true, this result is checked in the handle bars template,monitoring-data.handlebars, is true, a div element showing No Results Found is displayed
> Add no results found under data monitoring tab(connect #1868)

- Dashboard/app/css/main.scss
- Dashboard/app/js/templates/navData/monitoring-data.handlebars
In the detailed submission view the user does not need to see the Question ID, as this is an internal item we use and makes no sense or gives no value to the user. It only clutters her screen. The idea is to remove the question ID column to only show Questions and Answer.
Removed the question ID column to only show Question and Answer
> In monitoring tab remove question ID (connect #2385)

- GAE/appletBuild.xml
* There is one more reference to the caddisfly test file that prevents the exporterarpplet.jar from being build correctly
> Remove caddisfly file reference in exporterapplet build file (connect #2333)

- Dashboard/app/js/lib/controllers/survey-controllers.js
- Dashboard/app/js/lib/views/surveys/survey-group-views.js
- Dashboard/app/js/templates/navSurveys/form.handlebars
- Dashboard/app/js/templates/navSurveys/nav-surveys-main.handlebars
- Dashboard/app/js/templates/navSurveys/project.handlebars
Hitting the 'enter' key after changing survey/form title would trigger a page reload instead of saving the new title 
Hitting the 'enter' key now triggers a save of the new survey/form title
> Trigger save when user hits enter after changing survey/form title (connect #1929)

- GAE/war/WEB-INF/web.xml
* In the PR #2430, we deprecated the `SurveyServiceImpl` class and this results in an exception when starting up the application.
* We remove the servlet mapping that uses the deprecated class since its not used.
> Remove deleted servlet from web.xml (connect #2417)

- GAE/src/org/waterforpeople/mapping/app/web/rest/ActionRestService.java
Copied forms we're not always displaying for all users
Set the ancestor IDs of copied forms before triggering the survey copy
> Display copied forms for users (connect #1765)

- Dashboard/app/js/lib/controllers/data-controllers.js
- Dashboard/app/js/lib/views/data/inspect-data-table-views.js
- Dashboard/app/js/lib/views/data/monitoring-data-table-view.js
- Dashboard/app/js/lib/views/views.js
- Dashboard/app/js/templates/navData/monitoring-data-row.handlebars
- Dashboard/app/js/templates/navData/monitoring-data.handlebars
Once the user selects her survey and form in the Monitoring tab, she sees a list of data points. The first column in the list show the order/count of data points. This now shows as Not A Number.
The data points ordering now shows the numbers in the correct order
> Monitoring tab data point numbering shows as NaN (connect #2386)

- Dashboard/app/js/templates/navData/monitoring-data-row.handlebars
- Dashboard/app/js/templates/navData/monitoring-data.handlebars
Once the user selects her survey and form in the Monitoring tab, she sees a list of data points. The first column in the list show the order/count of data points. This now shows as Not A Number.
The  submission lists were not loading in the detailed views
> Monitoring tab data point numbering shows as NaN (connect #2386 )

- Dashboard/app/css/main.scss
When a search was done under the Inspect data tab or Monitoring tab with no results, "No results found" would be displayed with a line above it
Removed the border css code responsible for that line , in class .filterData ,in the main.css file
> Remove line above 'No results found' (connect #2452)

- Dashboard/app/js/templates/navData/data-subnav.handlebars
Bulk upload tab was right after the Inspect data tab under the Data sub-navigation.
Changed the position of Monitoring tab code in the data-subnav.handlebars file to right after the Inspect tab code
> Move monitoring tab after inspect data tab(connect #2467)

- Dashboard/app/js/lib/controllers/permissions.js
- Dashboard/app/js/lib/views/data/monitoring-data-table-view.js
- Dashboard/app/js/templates/navData/monitoring-data-row.handlebars
- Dashboard/app/js/templates/navData/monitoring-data.handlebars
Delete option was present at the monitoring tab and in the details dialog. However , the option wasn't working and the action point was to remove it all together to reduce data loss risks.
Removed the delete options in the monitoring templates and removed the delete function in the monitoring view.
> Cannot delete data point via monitoring tab (connect #2261)

- Dashboard/app/dashboard.html
- RELEASE_NOTES.md
Intergrity check on CartoDB libraries was failing causing maps not to load
Update the cryptographic hash for CartoDB libraries
> Hotfix for 1.9.28 CartoDB libraries integrity check failing (connect #2500)

- Dashboard/app/js/templates/navSurveys/nav-surveys-main.handlebars
Users were able to copy and move surveys to root folder
Disabled ability to copy survey to root folder by only availing the option when user is in destination folder
> Disable copying survey to root folder (connect #2464)

- Dashboard/app/js/templates/navSurveys/nav-surveys-main.handlebars
"Move/Copy here"  buttons not displayed in root folder
Display disabled "Move/Copy here" buttons in root folder
> Display disabled move/copy buttons when in root folder (connect #2464)

- Dashboard/app/js/lib/controllers/data-controllers.js
- Dashboard/app/js/lib/views/data/question-answer-view.js
- Dashboard/app/js/templates/navData/monitoring-data.handlebars
Both views are however quite inconsistent in how we show a form submission. In the Inspect data tab we show question groups and the questions that belong in them. In Monitoring tab we do not and the questions seem to appear in a random order.
The  repeated question groups are also shown properly with the repetition number.
>  Add question group to submission view in monitoring tab (connect #2387)

- GAE/src/com/gallatinsystems/surveyal/app/web/SurveyalRestServlet.java
- GAE/src/org/waterforpeople/mapping/domain/SurveyInstance.java
Data point geo location gets overriden when another question has a geolocation data even if it does not belong to the registration form
For the datapoint location, only use the geolocation data from a registration form and only if it is set as "use as datapoint location".
I have been digging and found where the SurveyedLocale geolocation gets updated but I am not sure I did not introduce any side effects. Would appreciate any extra suggestion.
NA
> Fix data point shown in wrong location (connect #2518)

- GAE/src/org/waterforpeople/mapping/app/web/rest/QuestionRestService.java
You could have two questions with variable names like "age" and "Age" at the same time.
Do a caseless compare when checking for already-existing variable names.
> [#839]Caseless search for existing variable names. (Connect #839)

- Dashboard/app/js/lib/views/surveys/question-view.js
Geolocation questions having the locale flag toggled by default regardless of whether or not user had unchecked "Use as data point location"
Remove code responsible for this
> Stop autochecking "Use as data point location" (Connect #2517)

- Dashboard/app/js/templates/navData/question-answer.handlebars
Both views are however quite inconsistent in how we show a form submission. In the Inspect data tab we show question groups and the questions that belong in them. In Monitoring tab we do not and the questions seem to appear in a random order.
The  repeated question groups are also shown properly with the repetition number.
> Fix alignment of the answers on the monitoring tab (connect #2387)

- GAE/src/com/gallatinsystems/survey/domain/Question.java
* The extra setter method `Question.setTranslationMap()` resulted in an exception because the property was not properly ignored.
* Remove the extra setter.
> Remove unnecessary setter (connect #2421)

- Dashboard/app/js/templates/navDevices/bootstrap-tab/survey-bootstrap.handlebars
Under the manual survey transfer tab (under Devices) , Select Survey and Preview Survey Selection were on opposites sides of the page. Preview Survey Selection is supposed to float next to survey selection section
Added enclosing div tags around the fieldset tags  for select survey and previewSurvey . Transferred classes affecting alignment from the fieldset tags to the div tags.
> Fixed layout issue in manual survey transfer tab(connect #2276)

- Dashboard/app/js/lib/views/data/monitoring-data-table-view.js
Similar to this issue: https://github.com/akvo/akvo-flow/issues/2372 the same happens for the Monitoring tab. The expectation is that once I go away from the Monitoring tab and then come back I will have no data points listed in the screen as I have not selected my survey yet and hit find. 
Once the user navigates to another page in Flow, the list of submissions does not show if he  comes back to the monitoring data  tab.
>  Submission lists remain on monitoring tab after navigation(connect #2531)

- Dashboard/app/js/lib/controllers/languages.js
Pijin and Tok Pisin languages were not available in the list of languages under form translations
Added Pijin and Tok Pisin to the languages object, FLOW.isoLangiagesDict in controllers/languages.js file.
> Added Pijin and Tok Pisin to list of languages in form translations(connect #2202)

- GAE/src/com/gallatinsystems/survey/domain/Question.java
Legacy varableName values might show up if new field was set to null.
Always remove legacy value if new one written.
> Issue/2551 improve variablename fallback (Connect #2551)

- Dashboard/app/js/lib/views/data/inspect-data-table-views.js
After fixing this issue and made this PR :https://github.com/akvo/akvo-flow/pull/2541  to clear the submission lists that remain after navigating away from the monitoring data tab.
Another bug came up where after viewing one submission list in detail in the monitoring data tab, it resurfaces  and appears in the inspect data tab when you navigate there.
Cleared the one submission list  that appears in the inspect data tab that comes as result of viewing the record in the monitoring data tab
> Submission lists remains on Monitoring tab after navigation (connect # 2531)

- Dashboard/app/js/lib/controllers/data-controllers.js
- Dashboard/app/js/lib/controllers/survey-controllers.js
- Dashboard/app/js/lib/views/data/inspect-data-table-views.js
- Dashboard/app/js/lib/views/data/monitoring-data-table-view.js
* For previewing response data under the monitoring tab, we required the correct question groups and questions to be loaded, however, the dashboard was loaded by default the questions and question groups from the first selected form in a survey, which did not always correspond to the data being previewed.
* We load the questions and question groups based on the form being previewed under the monitoring tab.
> Load question groups and questions correctly for monitoring tab preview

- Dashboard/app/js/lib/views/surveys/question-view.js
- Dashboard/app/js/templates/navSurveys/question-view.handlebars
- GAE/src/locale/en.properties
- GAE/src/locale/ui-strings.properties
Users were able to save questions even is the question text was empty
Prevent this by validating and disabling the save button if question text is empty
> Validate against empty question text (connect #2221)

- Dashboard/app/js/lib/views/reports/export-reports-views.js
- Dashboard/app/js/templates/navReports/export-reports.handlebars
Under the reports tab, when a user selected a date for the Data Cleaning section, the same date would show up under the data analysis section.
Changed from DateField to DateField2 in export-reports.handlebars in order to use an abstract function for the datepicker.
Changed from one instance of exportReportAppletView in the template to multiple instances for each report section
Added reportFromDate and reportToDate properties in exportReportAppletView and set them as the valueBinding for the date input fields  in the template
Added observers for reportFromDate and reportToDate inorder to change the min  and maxDates for the datepickers
> Fixed collection date set for both export options (connect #2363)

- Dashboard/app/js/lib/router/router.js
- Dashboard/app/js/templates/application/navigation.handlebars
- Dashboard/app/js/templates/navData/data-subnav.handlebars
- Dashboard/app/js/templates/navReports/reports-subnav.handlebars
Charts and report exports were under the reports tab on the main navigation
Move charts and report exports to under the data tab
> Move reports to under data tab (connect #2555)

- GAE/pom.xml
* The maven build was copying `appengine-web.xml` files in the existing `GAE/war` directory and overwriting any new config files that had been copied when executing the command `mvn appengine:update -DappId=<app_id>`
* In the maven packaging phase we exclude a config file if it exists in the current `GAE/war` directory
> Exclude config file in current war directory (connect #2406)

- GAE/src/META-INF/jdoconfig.xml
* Cascade levels not showing after importing them from a CSV file (even though they were correctly set in the datastore).
* We disable datanucleus caching and always query the cascade resources list from the datastore.
> Ignore datanucleus cached values and retrieve from datastore (connect #2606)

- GAE/src/org/waterforpeople/mapping/app/web/DeviceApplicationRestService.java
- GAE/src/org/waterforpeople/mapping/app/web/dto/DeviceApplicationRestRequest.java
- GAE/src/org/waterforpeople/mapping/dao/DeviceApplicationDao.java
- GAE/src/org/waterforpeople/mapping/domain/DeviceApplication.java
Old android devices will be deprecated in android 2.5.0 and have to be always served with 2.4.8 (latest version available for them)
the app will now send the android api code:
https://github.com/akvo/akvo-flow-mobile/issues/1091
the param is:
`&androidBuildVersion=27`
We need to check for this value and
if missing param -> latest version is 2.4.8 or empty if missing from datastore
if androidBuildVersion < 15 -> latest version is 2.4.8 or empty if missing from datastore
otherwise -> get the latest version from the datastore
NA
> Added logic to check for new androidBuildVersion param (connect #2603)

- scripts/deploy/deploy.sh
- Instead of dealing with empty 'null' values via `-z` comparison
we use a predefined missing value `unknown`
> [#2562] Fix logic dealing with GH_* environment variables (connect #2562)

- .dockerignore
docker is sending the whole current directory when doing a build and the
current directory can get quite big (up to 2gb) after compiling all the
classes and running some of the data scripts.
For building the images, we only really use the Dashboard/Gemfile*. All
other files are made available to Docker because we mount the whole source
directory.
Fixes #2633
> [#2633] .dockerignore all files

- Dockerfile
- ci/bootstrap-build.sh
- ci/deploy.sh
- We explicitly use `--entrypoint` pointing to the mounted bash
script, instead of Dockerfile
- We also mount the host $HOME/.m2 under /root/.m2 just in case
someone wants to run the build in MacOS
> [#2628] Define entrypoint at runtime instead of Dockerfile (connect #2628)

- .gitignore
- ci/devserver.sh
- This avoids the need of downloading a 45MB file every time we
clean the GAE/target folder
> [#2651] Cache local_db.bin under GAE/tmp folder (connect #2651)

- Dashboard/app/js/lib/controllers/permissions.js
Permission set at root level overriding permissions set for specific surveys and forms down the folder structure
When loading specific forms and surveys, check if there are specific permissions set beyond the root level
> Permissions set at root level override permissions set down the nest (Connect #1582)

- GAE/src/com/gallatinsystems/surveyal/dao/SurveyedLocaleDao.java
- GAE/src/org/waterforpeople/mapping/app/web/rest/PlacemarkRestService.java
* All datapoints returned when a request is made to the maps backend
* We filter datapoints based on a `surveyId` thats provided in the request.  
* When maps are accessed through the publicly visible page, no survey is provided.  Here we return all datapoints but without any details of internal identifiers and therefore a non-authorized user can only see the datapoints but cannot access the associated content.
> Filter datapoints for maps backend by `surveyId` (connect #2661)

- scripts/deploy/deploy.sh
Setting scaling to basic scaling with a maximum of one server and 
a idle timeout to 5 mins
Fixes #2670
> [#2670] Dataprocessor backend should use basic autoscaling

- Dashboard/app/js/lib/views/maps/map-views-common.js
* An on click handler is defined to clear the map when clicked.  This also causes the maps points to be removed. 
* Take out the on click handler.
> Do not clear cartodb maps when clicking on a point (connect #2661)

- Dashboard/app/js/lib/controllers/permissions.js
- Dashboard/app/js/lib/controllers/survey-controllers.js
When creating a form, formId is not generated till the form has been created in the database
~Assume new form is being created if a form object without a formId is passed for checking~
Add `ancestorIds` to the newly created form, so that parent permissions are applied to the new form.
> Allow form editing when creating new form (connect #2677)

- .travis.yml
- Dockerfile
* By using major or major.minor versions on apk packages we reduce
the amount of broken builds. apk will work in _fuzzy_ mode filling
the blanks of the rest of the available packages
* Since we're building a docker container with all dependencies, there
is no need to set the travis build to be a java one. No java setup
is needed.
> Use fuzzy version for apk packages (connect #2704)

- GAE/src/org/akvo/flow/domain/DataUtils.java
Fixes #2722
The export process ignores any invalid caddisfly value. No action to be performed by developers so changing the log level to warn.
> Remove sentry errors for "Failed to parse the caddisfly response"

- GAE/src/org/akvo/flow/rest/ReportRestService.java
- GAE/src/org/akvo/flow/rest/dto/ReportTaskRequest.java
- GAE/src/org/akvo/flow/servlet/ReportServlet.java
Filename was lost in transfer after we switched from beanutils data copying.
Add it.
> [#2719]Fix filename transfer. (Connect #2719).

- GAE/src/org/waterforpeople/mapping/dataexport/ExportImportUtils.java
Fixes #2717.
Log issue at info level instead of error level
> Remove sentry errors for "Value is not a valid timestamp" (Connect #2717)

- Dashboard/app/js/lib/controllers/reports-controllers.js
Refreshing reports every 5s if a report was in progress or queued. This would however result in looping calls which would weigh down on the browser if a report stays in queue for too long. We need to rethink how to tackle this
Remove the refreshing
> Stop refreshing list to check for processed reports (connect #2505)

- GAE/pom.xml
- README.md
Also, removing gpg as it breaks when running "mvn install" locally and it
is not being used during deployment
Fixes #2748
> Document workflow when working with Java Report classes

- Dashboard/app/js/lib/controllers/survey-controllers.js
- Dashboard/app/js/lib/router/router.js
Only survey groups and cascade resources pulled when dashboard is loaded
Add surveys to items pulled on dashboard load
> Preload surveys on dashboard load (connect #2754)

- .gitattributes
Tell git to always use LF for shell scripts 
See #2807
> [#2807] Tell git to always use LF for shell scripts

- GAE/pom.xml
* The SSL certificate at `https://nexus.geomatys.com/repository/geotoolkit` is expired so we upgrade the `jts` dependency to one available on maven central
> Upgrade the version of jts dependency (connect #2809)

- GAE/src/org/akvo/flow/rest/dto/ReportTaskRequest.java
- GAE/src/org/akvo/flow/servlet/ReportServlet.java
We should delay successive attempts so that transient problems have time to clear up.
Also, after a closer look, Long is not needed for attempt counting. 
Add a 30s delay. Switch to int.
> [#2779]Add a delay. Use int instead of Long. (Connect #2779)

- Dashboard/app/dashboard.html
- Dashboard/app/js/lib/views/maps/map-views-common-public.js
- Dashboard/app/js/lib/views/maps/map-views-common.js
- Dashboard/app/public.html
We are currently using mapbox v1.6.1 that is based on leaflet.js 0.7.2. The latest version of mapbox is v3.1.1 that includes improved features provided by leaflet.js and other new leaflet plugins, e.g. clustering plugins, placemarker plugins, and vector maps. We could build a simple prototype to see whether it takes a lot of effort to upgrade the library.
I changed the mapbox library from v1.6.1 to latest version v3.1.1
> Upgrading to the latest mapbox library(connect #2769)

- Dashboard/app/css/main.scss
- Dashboard/app/js/lib/views/data/inspect-data-table-views.js
- Dashboard/app/js/lib/views/data/monitoring-data-table-view.js
- Dashboard/app/js/templates/navData/inspect-data.handlebars
- Dashboard/app/js/templates/navData/monitoring-data.handlebars
In the Monitoring  and inspect data tab,  the user must select a survey to be able to see the data points. Currently if she does not select anything and hits 'Find' we show 'No results found'. This error message should apply to when there is no data for a survey and not when a survey is not selected.
* highlight the dropdown when the user hits Find but did not select a survey
* ensure that No results found only shows when a survey is selected that is empty, has no data submitted to it
> Indicate survey must be selected via monitoring tab and inspect-tab(connect #2455)

- Dashboard/app/js/lib/views/reports/export-reports-views.js
- Dashboard/app/js/templates/navReports/export-reports.handlebars
Under the export reports tab, if one of the download options was selected without first selecting the survey:
-Data cleaning export: nothing would happen
-Data analysis export: a pop up dialog with the message error generating report would be displayed
-Comprehensive report: a pop up dialog with the message 'your report is being prepared' would be displayed
-Geoshape data: a pop up dialog with the message 'please select a form and a geoshape question' would be displayed
-Survey Form: a pop up dialog with the message 'you must select a survey to run a report' would be displayed
Show the highlight box around the survey dropdown when the survey is not selected yet the user is trying to generate the exports
>  Indicate form must be selected via exports page(connect #2380)

- Dashboard/app/js/lib/views/reports/export-reports-views.js
- Dashboard/app/js/templates/navReports/export-reports.handlebars
…filter
Challenge is that when the user clicks the generate button in the exports tab without first selecting the survey forms, the survey selection filters get highlighted but the user cannot currently see it unless she scrolls up.
Scroll back to the top to show the highlighted survey filters so that user can be ware that he has not yet selected the survey.
> Hotfix for indicate the form must be selected in the export tab(connect #2380)

- Dashboard/app/js/lib/controllers/maps-controllers-common.js
* When one clicked on a datapoint belonging to a non-monitoring survey, the responses were not correctly retrieved because the logic always assumed a monitoring survey.
* For the non-monitoring surveys, we take the first (and only) form instance for a data point to correctly retrieve its associated responses
> Load data for non monitoring surveys (connect #2680)

- Dashboard/app/js/lib/views/surveys/survey-group-views.js
User has to open a created folder then navigate back to parent folder to be able to edit created folder's name
Hitting enter when editing folder name doesn't save the change as should based on f767d161603099324783f93414f7baf793dc3caf
Enable editing folder name immediately after creating it
Enable saving folder name by hitting enter
> Enable editing created folder name when creating it (connect #2875)

- Dashboard/app/js/lib/views/data/inspect-data-table-views.js
In the inspect data tab, when a user selects a form then clicks on "Find", the dashboard makes a call to the questions endpoint first then to the survey instances resulting in the loading animation disappearing before the survey instances have finished pulling
We already have the questions pulled when we selected the form via the filter so remove the unnecessary call
> Remove delay between loading animation and display of submissions (connect #2827)

- Dashboard/app/js/lib/views/views.js
Caddisfly response displaying as a json string on the details panel of maps tab
Changed how we check for "image" property on caddisfly response
> Render caddisfly response on maps tab (#1750)

- GAE/src/org/akvo/flow/events/EventLogger.java
Errors were logged for each failed notification, *or* each notification that was not possible because of missing or empty config parameter, cluttering the logs.
Remove logging of error if no config.
> [#2906]Remove always logging an error(Connect #2906)

- Dashboard/app/js/lib/controllers/survey-controllers.js
When a user moved a question prior to selecting manage translations, the options questions appeared out of order in the form translations, with some options appearing above their respective question and in some cases below
Changed the equation for question order in survey-controllers.js by adding 1 in order to guarantee that the questionOption appear below the questions.
> Options reposition in translations page (connect #1983)

- GAE/src/org/waterforpeople/mapping/app/web/rest/CascadeNodeRestService.java
- GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
We have always set the code from the name for cascade nodes.
With a recent change this became visible in the data cleaning report.
Stop setting codes like that.
For backwards compatibility, go back to hiding codes when identical to names.
> Issue/2926 cascade codes (Connect #2926)

- Dockerfile
Travis build failed
Go to 17.5
> [#2956]Bump py-openssl version to 17.5

- Dashboard/app/js/lib/views/views.js
Signature responses not loading on maps due to response parsing set to split folder separation character
Set condition to parse only non-signature responses
> Only split folder separate character for non-signature type responses (connect #2937)

- Dashboard/app/js/lib/views/views.js
Escape characters being removed even for signature responses which are part of the response string
Stop removing escape characters for signature responses
> Stop removing escape characters for signature responses (connect #2937)

- Dashboard/app/js/lib/controllers/survey-controllers.js
- Dashboard/app/js/templates/navSurveys/project.handlebars
Forms ordered chronologically on surveys tab
Order forms alphabetically but always have the registration form first
> Order forms alphabetically on surveys tab (connect #2917)

- ci/mvn-deploy.sh
* The version (zip) package used for deployment was not being generated, which means deployments would not work because the set of files for that version would not be found on the remove bucket.
* Correctly generate version package with the git tag.
> [#1502] Add missing variable to generate version package

- GAE/src/com/gallatinsystems/common/Constants.java
- GAE/src/org/waterforpeople/mapping/analytics/dao/SurveyQuestionSummaryDao.java
- GAE/src/org/waterforpeople/mapping/app/web/DataProcessorRestServlet.java
- GAE/src/org/waterforpeople/mapping/dao/SurveyInstanceDAO.java
Long/JSON results are not handled when looking up summary data.
Take apart JSON results and handle it without a crash if it still is too long.
Also moved the task-submitting code to DataProcessorRestServelet, where the task will be handled.
> [#3038]Handle long option results

- GAE/src/org/waterforpeople/mapping/dataexport/ExportImportConstants.java
- GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
- GAE/src/test/java/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporterTests.java
Forms with the first or all groups repeatable were not imported correctly
Handle that, chiefly by changing the verify() method.
> [#2995]Fix header validation for all-repeatable forms.

- scripts/data/lets-encrypt-app-url.sh
- scripts/data/my_lets-encrypt-app-url.sh
- scripts/data/src/org/akvo/gae/remoteapi/LetsEncryptAppUrl.java
S3 will stop supporting unencrypted fetches.
Iterate over app URLs and change http: to https:
> [#3040]Add script to make all app URLs https.

- scripts/data/split-assignments.sh
- scripts/data/src/org/akvo/gae/remoteapi/SplitAssignments.java
Assignments must not contain forms from different surveys.
Datascript to split them.
> [#3107]Implement script for splitting assignments between surveys.

- Dashboard/app/js/lib/views/devices/assignment-edit-views.js
- Dashboard/app/js/lib/views/devices/assignments-list-view.jsx
- Dashboard/app/js/templates/navDevices/assignment-edit-tab/assignment-edit.handlebars
- GAE/src/locale/en.properties
- GAE/src/locale/ui-strings.properties
Save option available even when no assignment name is set resulting in a sometimes empty assignments 
Add validation for assignment name
> Disable saving nameless assignment (connect #3132)

- Dashboard/app/js/lib/models/models.js
* Surveys loaded one by one making loads of unnecessary requests to the backend
* Create computed property that defines property for which all the surveys were previously loaded.
> [#3139] Stop unnecessary loading of all Survey entities when forms are loaded

- GAE/pom.xml
- GAE/src/com/gallatinsystems/framework/dao/BaseDAO.java
* Entities with known IDs retrieved one by one by repeatedly making requests to the datastore for each entity.
* We make a single request to the datastore with the list of IDs
> [#3142] Retrieve entities with known IDs in a single batch request

- Dashboard/package.json
Upgrading from babel 6 to 7 requires deeper dependencies upgrade which is causing builds to sometimes fail
revert to v6 for now
> Remove dependency causing build failure connect (#3138)

- GAE/src/org/akvo/flow/events/EventLogger.java
- GAE/src/org/akvo/flow/events/EventUtils.java
- scripts/data/src/org/akvo/gae/remoteapi/DataStoreWithUnilog.java
- scripts/data/src/org/akvo/gae/remoteapi/RemoteAPI.java
See #3176
Wrapping the default datastore into one that is Unilog aware
Requires no change in any of the current or future data scripts.
Any change in an entity will imply x2 writes, one for the entity itself and
one for the event.
Events are added after changes in the entities.
Notify Unilog of new events, using the unilog url found in the appengine-web.xml, if exists.
> Data scripts to update Unilog

- Dashboard/app/js/lib/models/models.js
- Dashboard/app/js/lib/views/devices/assignment-edit-views.js
- Dashboard/app/js/lib/views/selectors/device-selector.jsx
- Dashboard/app/js/lib/views/selectors/forms-selector.jsx
`surveys` and `devices` properties from the survey_assignments endpoint changed but not handled on front-end causing forms and devices selection not to work
handle both
> Handle changed properties

- scripts/data/src/org/akvo/gae/remoteapi/SplitAssignments.java
Need to update the field names as used by #3166.
> [#3173]Update field names in all entries.

- scripts/data/src/org/akvo/gae/remoteapi/SplitAssignments.java
Messed up the logic when I removed the forceSplit boolean.
Fix it. Improve comment.
> [#3173]Fix logic.

- GAE/pom.xml
```
WARNING!!! version ranges found for:
[org.akvo.flow/akvo-flow "v1.9.49-211-g94e20820" :classifier "classes" :exclusions [log4j commons-logging commons-codec commons-io]] -> [com.fasterxml.jackson.core/jackson-core "[2.9.9,2.9.9]"]
Consider using [org.akvo.flow/akvo-flow "v1.9.49-211-g94e20820" :classifier "classes" :exclusions [commons-logging log4j commons-io commons-codec com.fasterxml.jackson.core/jackson-core]].
[org.akvo.flow/akvo-flow "v1.9.49-211-g94e20820" :classifier "classes" :exclusions [log4j commons-logging commons-codec commons-io]] -> [com.fasterxml.jackson.core/jackson-databind "[2.9.9,2.9.9]"]
Consider using [org.akvo.flow/akvo-flow "v1.9.49-211-g94e20820" :classifier "classes" :exclusions [commons-logging log4j commons-io commons-codec …
```
> [#3098] Use specific version of Jackson library

- .dockerignore
The content of the node_modules folder is being sent to docker for the build,
but it is not used as that folder is mounted as a volume.
The folder happens to be ~500mb in size, which means that in my box a
`docker-compose up --build -d` takes ~50 secs. By ignoring this folder, the
same command takes ~6 secs.
Fixes #3244
> Exclude node modules from docker build

- GAE/src/org/akvo/flow/xml/XmlOptions.java
- GAE/src/org/akvo/flow/xml/XmlQuestion.java
- GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
- GAE/src/org/waterforpeople/mapping/dataexport/SurveySummaryExporter.java
Option read from published XML were not split into columns.
Image filenames required a slash to be put into a report.
Copy option flags around.
Better code for stripping filename paths.
> [#3260]Fix data exporter bugs.

- GAE/src/com/gallatinsystems/survey/dao/QuestionDao.java
- GAE/src/com/gallatinsystems/survey/dao/SurveyDAO.java
- GAE/src/org/waterforpeople/mapping/app/web/SurveyAssemblyServlet.java
* We remove code that is querying the `QuestionHelpMedia` entity that is no longer used.
* Rename the function to match domain names (Form)
* Remove unused import
> [#3115] Refactor form loading code to improve performance

- Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
`FLOW.selectedControl` was a redundant complexity, replaced it with normal javascript array for device and form selector.
To test:
- Assert all form functionality works as before
- Assert all device functionality works as before
> [#3295] remove redundant state handler

- Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
The issue was caused by JavaScript mistype. In the assignment-UI-view, the `deviceInAssignment` method the argument received was a number and the items in the array as a string. So type did not match
The solution was to convert the argument to a string to make it match the item in the array. Also removed some `console.log`s
> [#3302] - Fixed saved devices not showing

- GAE/src/com/gallatinsystems/surveyal/domain/SurveyedLocale.java
Too much content for the display name made it overflow the 1500 char storage limit for String. Length check was bypassed by assembleDsiplayName() method.
Fix that, and bump the check from old 500-char limit.
> [#3317]Go via setter for truncation check. Use modern 1500-char limit.

- docker-compose.yml
Fake flow services were not responding to the DNS name in the local instance config file.
Admittedly, the difference between responding 200 to everything and then doing nothing, and not being reachable at all, is minor. Still, it results in an error in flow.
Add that.
> [#2919]Answer to name used in local dev config file. (connect #2919)

- Dashboard/app/js/lib/components/devices/AssignmentsEditView/styles.scss
Add padding to `.device-action-page .body` to remove overlap with footer
> [#3339] - Fix footer on add/edit tab

- GAE/src/org/akvo/flow/xml/XmlForm.java
- GAE/test/org/akvo/flow/xml/FlowXmlObjectWriterTests.java
* Registration survey id missing form the generated XML form definition
* `registrationSurvey` attribute is now included in XML form
> [#3316] Add registration survey attribute to XML form

- Dashboard/app/js/lib/components/devices/AssignmentsEditView/styles.scss
A gray background-color show on the back button on the assignments page.
Make the button transparent.
> [#3376] - removed background color from assignment back button in Firefox

- GAE/src/org/waterforpeople/mapping/app/web/TestHarnessServlet.java
There was still some references to `dataprocessor` backend.
> [#3385] Remove references to `dataprocessor` backend

- .travis.yml
- ci/bootstrap-build.sh
- ci/build.sh
- docker-compose.yml
- Update to the latest akvo/akvo-flow-builder image that is based
on a published google/cloud-sdk
- Remove references to ruby build process, e.g. RAKEP_MODE BUNDLE etc
We're now using `node` to bundle our client application
- Use `npm ci` instead of `npm install` as part of the build
https://docs.npmjs.com/cli/ci.html
- Cache `$HOME/.npm` to speed up builds
> [#3380] Update dev image + code clean up

- GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyedLocaleRestService.java
The since string was used for two different lookups.
Use it only for the same lookup it was obtained from.
> [#3408]Do not use "since" parameter in identifier search.

- Dashboard/app/js/lib/components/devices/AssignmentsEditView/styles.scss
Scrolling down to find the Action button is bad UX
Making the action button fixed to the bottom of the screen and always visible to the user
> Issue 3413/make device action button stick to bottom

- GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyedLocaleRestService.java
surveyGroupId param was ignored when search param weas present.
Pass it to the lookup method.
> [#3408]Use surveyGroupId when searching.

- GAE/war/WEB-INF/datastore-indexes.xml
Search plus surveyGroupId lookup needs db indices.
Add indices.
> [#3408]Add db indices.

- Dashboard/webpack.config.dev.js
- Dashboard/webpack.config.prod.js
No contentHash in the admin production build bundle
Added contentHash to only make the server fetch for new bundle if the hash changes (aka code changes)
> [#3416] - add contentHash and other caching options for production build

- Dashboard/webpack.config.prod.js
Unnecessary module splitting config was added to webpack config which was breaking the build
Remove module splitting
> [#3416] - remove module splitting from webpack

- Dashboard/app/js/lib/components/devices/AssignmentsEditView/styles.scss
> [#3446] - make assignment name border more visible

- GAE/src/com/gallatinsystems/framework/rest/AbstractRestApiServlet.java
- GAE/src/com/gallatinsystems/framework/rest/RestRequest.java
Some requests time out due to hitting the one minute deadline on GAE
We add the possibility to create a task by simply adding a parameter to the request.  This works for servlets that are extended from com.gallatinsystems.framework.rest.AbstractRestApiServlet.  Also right now we support only the ones that are secured.
> [#3451] Enable redirecting a servlet request to run as a task

- Dashboard/app/js/lib/components/devices/AssignmentsEditView/screens/AddDevices.jsx
- Dashboard/app/js/lib/components/selectors/DeviceSelector/DeviceAccordion.jsx
- Dashboard/app/js/lib/components/selectors/DeviceSelector/index.jsx
devices seem to be sorted in descending order, i.e from z -> a rather than from a-> z. This was caused by javascript sorting object keys by default.
Sort the device group by names rather than by ID
> [#3447] - sort device groups

- GAE/pom.xml
* `devserver.version` is not longer a valid property with the new SDK
* `GAE_FULL_SCAN_SECS` is an environment variable
> [#555] Update pom definition

- Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
Bug with FolderSurveySelector having a survey still selected after selecting the default option (`Choose a folder or survey`)
When default option is selected, clear the currently selected option
> [#3483] - remove selected survey group when default folder is selected

- Dashboard/app/js/lib/components/devices/AssignmentsEditView/styles.scss
Section close button in assignments was big and in your face
Make it smaller and less in your face
> [#3506] - make close button smaller

- Dashboard/app/js/lib/components/selectors/DeviceSelector/DeviceAccordion.jsx
Device group according was open by default causing a lot of visual noise in the page
Keep device group closed by default
> [#3505] - keep device groups closed by default

- Dashboard/app/js/lib/router/router.js
- Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
- Dashboard/app/js/lib/views/devices/assignments-list-view.jsx
The new `Assignment` behavior is different than the rest of the
application, e.g.  When creating a new `Survey`, we create and commit
the record, we get a the new `keyId` from the server and then we ask
the user to "edit" it.
In the case of `Assignment` we create a new record in the client and
we don't commit it until the user clicks the "Save" button or the user
navigates away triggering an implicit `FLOW.store.commit()`.
Since we don't want to save partially filled `Assignment` if the user
navigates away, we want to discard that record.
Ember Data has a concept of "transaction" and we use it to deal with
this exception.  When creating a new `Assignment` we do it within a
transaction and we discard if the user navigates away.
>  Because newly created records are dirty from the time they …
> [#1223] Use a 'transaction' for new Assignment

- GAE/src/com/gallatinsystems/surveyal/dao/SurveyedLocaleDao.java
A common pitfall when trying to compare strings is to use `==`
operator, but this one is for checking if to objects are the same
"reference".  Most of the cases we want to use `.equals()` function.
In this particular issue the check `!= ""` was evaluating that the
passed string parameter `since` was the same refence, so the code
prepared a cursor of only 20 entities.
Fixing this problem now leads to a different UX problem that the user
needs to click one by one a pontential large list of checkboxes. This
problem will be fixed in a different changeset.
More info: https://stackoverflow.com/questions/513832/how-do-i-compare-strings-in-java/513839#513839
> [#3524] Use `equals` instead of `==` for String comparison

- Dashboard/app/js/lib/components/devices/AssignmentsEditView/styles.scss
Action buttons fixed at the bottom were hidden on screens with smaller height
Use `view-height` to make the buttons more responsive and visible
> [#3497] - make action buttons fixed in assignments

- Dashboard/app/js/lib/components/devices/AssignmentsEditView/screens/FormSection.jsx
- Dashboard/app/js/lib/components/devices/AssignmentsEditView/styles.scss
- Dashboard/app/js/lib/components/selectors/FormSelector/index.jsx
Folder selector width was limited to 45% of the container
Make `folder-selector` width full-width
> [#3502] - make folder selector stretch to fit screen

- GAE/src/org/akvo/flow/api/app/DataPointServlet.java
- GAE/src/org/akvo/flow/api/app/DataPointUtil.java
- GAE/src/org/akvo/flow/api/app/SurveyedLocaleServlet.java
- GAE/test/org/akvo/flow/api/app/DataPointUtilTest.java
The `/datapoints` endpoint will filter form instances by the
assigned forms instead of returning all. The exception is the
old `/surveyedlocale` used by old apps that will keep returning
all the data.
> [#3528] Filter form instances by assigned forms

- Dashboard/app/js/lib/components/devices/AssignmentsEditView/__partials/SidebarDropdown.jsx
Sidebar dropdowns were opened by default
Make the dropdown closed by default
> [#3538] - make device groups on sidebar closed by default

- Dashboard/app/js/lib/components/devices/AssignmentsEditView/screens/AssignDatapoints/SearchDatapoints.jsx
- Dashboard/app/js/lib/components/devices/AssignmentsEditView/screens/AssignDatapoints/index.jsx
We "cache" the ids of the already assigned datapoints and use it as
`props` for the Component. When rendering the list of available
datapoints, we filter out those already assigned.
> [#3521] Filter search result - Don't include already assigned

- Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
- We don't _reset_ the selected data points when changing the Survey
- Reset the value to All data points if the user switches the Survey to a different value
> [#3547] - reset datapoints assignments when new folder is selected

- Dashboard/app/js/lib/analytics.js
- Dashboard/webpack.config.dev.js
- Dashboard/webpack.config.prod.js
We were using fixed ids for both local and prod environment
Use env variables for controlling analytics site-ids
> [#3552] - use environmental variable for site id

- Dashboard/app/js/lib/views/data/inspect-data-table-views.js
- Dashboard/app/js/lib/views/data/monitoring-data-table-view.js
- Dashboard/app/js/lib/views/reports/export-reports-views.js
- Dashboard/app/js/lib/views/stats/new-stats.jsx
No way to track user actions around data and stats exports
Add tracking methods for Data exports, Stats and Data view
Due to prettier being prettier, they're formatting changes in this PR
> Issue 3556/track user interactions in flow

- GAE/src/com/gallatinsystems/common/util/MD5Util.java
- GAE/src/com/gallatinsystems/framework/servlet/RestAuthFilter.java
- GAE/src/com/gallatinsystems/survey/domain/Survey.java
- GAE/src/com/gallatinsystems/survey/domain/WebForm.java
- GAE/src/org/akvo/flow/util/OneTimePadCypher.java
- GAE/src/org/waterforpeople/mapping/app/web/rest/QuestionRestService.java
- GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyNotValidAsWebformException.java
- GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyRestService.java
- GAE/test/org/akvo/flow/util/OneTimePadCypherTest.java
Relates #3562 
Besides setting up a new endpoint  in `SurveyRestService`  `GET, value = "/{id}/webform_id"` and the logic to ofuscate the SurveyId value using an OneTimePad encrypted url encoded algorithm, there are changes to take care of the new Survey db boolean column `webform` that depends on survey column types support (currently don't supported `CASCADE, GEOSHAPE, SIGNATURE, CADDISFLY`)
Changes once integrated with UI branch
New boolean column `webform` in Survey Table
> Use random url for webforms

- GAE/src/com/gallatinsystems/survey/domain/WebForm.java
- GAE/src/org/waterforpeople/mapping/app/web/SurveyAssemblyServlet.java
- GAE/src/org/waterforpeople/mapping/app/web/rest/QuestionRestService.java
- GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyRestService.java
- Remove Cascade question type as not allowed
- Validate survey (and update webform boolean column db) only on `surveys/{id}/webform_id` and [publishing survey logic](https://github.com/akvo/akvo-flow/blob/issue-3562/GAE/src/org/waterforpeople/mapping/app/web/SurveyAssemblyServlet.java#L197) (thus webform python backend only uses s3 survey published definitions)
> Fix webform validation conditions and refactor logic application contexts

- Dashboard/app/js/lib/views/views.js
- Dashboard/app/js/templates/navSurveys/nav-surveys-main.handlebars
* The `eventManager` is a shared instance therefore the tooltip text was being overwritten. i.e. all tooltips contained text of the last tooltip loaded on a page. 
* Save tooltip text in a new attribute and retrieve it on `mouseover` a tooltip element
* Replace handlebars comment with HTML comment to fix wrong rendering
> [#3593] Fix tooltip text

- GAE/pom.xml
- GAE/src/com/gallatinsystems/surveyal/dao/SurveyedLocaleDao.java
- GAE/src/org/akvo/flow/api/app/DataPointRequest.java
- GAE/src/org/akvo/flow/api/app/DataPointResponse.java
- GAE/src/org/akvo/flow/api/app/DataPointServlet.java
- GAE/src/org/akvo/flow/api/app/SurveyedLocaleServlet.java
- GAE/src/org/akvo/flow/dao/SurveyAssignmentDao.java
- GAE/test/org/akvo/flow/api/app/DataPointServletTest.java
* Frequent timeouts while downloading datapoints from the device
* Not all datapoints downloaded
* Reduce the number of datapoints downloaded in a single batch to 30
* Use the `cursor` query parameter to enable selective/incremental downloading
> [#3608] Download datapoints

- GAE/src/com/gallatinsystems/framework/servlet/RestAuthFilter.java
- GAE/test/com/gallatinsystems/framework/servlet/RestAuthFilterTests.java
- GAE/test/org/akvo/flow/api/app/DataPointServletTest.java
* Attempting to download datapoints with a cursor always results in a `401 Authorization failure` error.
* Rewrite the `RestAuthFilter` logic to make it more clear and add tests cases for authentication including some using cursors.
* Add rest cases for the retrieval of datapoints in various scenarios: when there are no datapoints present in the datastore, when they are larger than the batch size, when datapoints are updated, and when there are no more datapoints to retrieve from a batch.
> [#3608] Download datapoints with cursor

- GAE/src/org/akvo/flow/api/app/DataPointServlet.java
- GAE/test/org/akvo/flow/api/app/DataPointServletTest.java
* When there were no more datapoints to return from a cursor based query, and the extra call is made to verify this, the backend would return an error "No datapoints assignments found".
* Fix the backend such that when making subsequent queries using cursors to retrieve datapoints from the backend, the backend should return a list of results of size 0 to indicate that there are no more datapoints to retrieve and that this cursor should be saved and will be used the next time there is need to retrieve datapoints.
> [#3608] Return empty results list when no more datapoints to return

- Dashboard/app/js/lib/components/devices/AssignmentsEditView/screens/AssignDatapoints/index.jsx
- Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
When loading datapoints more than 710 data points, there's a 413 error (request query too large)
Add pagination, so the user only fetch 30 at a time
> [#3629] - add pagination for datapoints

- Dashboard/app/js/lib/components/devices/AssignmentsEditView/screens/AssignDatapoints/index.jsx
- Dashboard/app/js/lib/components/devices/AssignmentsEditView/screens/EditDatapoints.jsx
- Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
Due to the new load more feature, we had 2 arrays controlling datapoints which led to a bug from assigning and editing datapoints
Use only one array with a load-and-replace method to load more
> [#3629] - fix regression with load more functionality in datapoints

- GAE/src/org/akvo/flow/api/app/DataPointUtil.java
- GAE/src/org/waterforpeople/mapping/dao/SurveyInstanceDAO.java
- GAE/test/com/gallatinsystems/surveyal/dao/SurveyInstanceDAOTest.java
In instances when lots of form instances per data point, we can't
serve the request in less than 60s. The traces show lots of datastore
requests to get the most recent N submissions.
Closes #3528
> [#3528] Send only registration form data

- GAE/src/org/akvo/flow/api/app/DataPointUtil.java
* Ideally removing the extra query speeds up the entire time to complete the request.
> [#3645] Remove an extra query for datapoints that have already been retrieved

- GAE/src/com/gallatinsystems/framework/dao/BaseDAO.java
- GAE/src/com/gallatinsystems/surveyal/dao/SurveyedLocaleDao.java
- GAE/src/org/akvo/flow/api/app/DataPointOnlyServlet.java
- GAE/src/org/akvo/flow/api/app/DataPointServlet.java
- GAE/src/org/akvo/flow/api/app/DataPointUtil.java
- GAE/test/org/akvo/flow/api/app/DataPointUtilTest.java
using offset to return assigned datapoints in batches of 30 as query by key does not allow to query with a cursor
> [#3652] using offset to return assigned datapoints

- Dashboard/app/js/lib/components/reusable/OfflineIndicator/index.jsx
- Dashboard/app/js/lib/views/surveys/offline-state.jsx
- Dashboard/app/js/lib/views/views.js
- Dashboard/app/js/templates/navSurveys/nav-surveys-main.handlebars
Tell user is he/she is online or offline
This is a simple implementation of using navigator.onLine.
It wouldn't work on some older browsers, but we would handle this edge case in future modifications
> [#3624] - add a basic text to tell user if he/she is offline

- GAE/src/org/waterforpeople/mapping/app/web/EnvServlet.java
* When the System.property `templateIds` is not defined (null) we set a default value to `[]`
Closes #3667
> [#3667] Set a default value for environment setting

- Dashboard/app/js/lib/controllers/survey-controllers.js
- Dashboard/app/js/lib/views/surveys/question-view.js
- Dashboard/app/js/templates/navSurveys/question-view.handlebars
- GAE/src/locale/ui-strings.properties
React accordingly in related copied forms to editable question options
If a template is copied, questions marked as immutable are not editable
Don't send the immutable parameter in the survey copy request
Co-authored-by: Emmanuel Mulo <emmanuel@akvo.org>
Co-authored-by: Daniel Sunnerek <daniel@akvo.org>
Co-authored-by: Iván Perdomo <ivan@perdomo.me>
Co-authored-by: Valeria Rogatchevskikh <valeria@akvo.org>
> [#3637] Add immutable flag to question template

- GAE/src/org/waterforpeople/mapping/app/web/DataProcessorRestServlet.java
- GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyInstanceRestService.java
- GAE/src/org/waterforpeople/mapping/dao/SurveyInstanceDAO.java
* We delete the main entity (`SurveyInstance`) in the request thread
and delegate the removal of child/dependent objects to a Task
Co-authored-by: Valeria Rogatchevskikh <valeria@akvo.org>
Closes #3697
> [#3697] Async delete of form instances

- GAE/src/org/akvo/flow/xml/XmlHelp.java
Translations are shown duplicated in the xml file
Use a map by language so only one translation per language is shown
> [#3685] fix translation duplicates in xml files

- GAE/src/com/gallatinsystems/survey/dao/SurveyUtils.java
- GAE/test/com/gallatinsystems/surveyal/dao/SurveyUtilsTest.java
- GAE/test/org/akvo/flow/api/app/DataStoreTestUtil.java
We were using a map to store copied groups so the group order was lost,
using a list now
Added a test
Co-authored-by: Juan A. Ruz <juanantonioruz@gmail.com>
> [#3689] Fix different group dependencies are broken

- scripts/data/src/org/akvo/gae/remoteapi/FixCopyDependency.java
* In one of the instances there are more than one copy resulting on a
`PreparedQuery$TooManyResultsException`
* This problem was produced by broken copies of a survey and the retry
of the Task doing the copy
* Workaround the problem by using a `.asList()` and grabbing the first element
> [#3689] Get the first element of a result set if present

- Dashboard/app/js/lib/views/reports/export-reports-views.js
- Dashboard/app/js/templates/navReports/report.handlebars
When a report export fails, the system generates a `message` that is
not shown to the user.
> [#3705] Show report error messages

- GAE/src/org/waterforpeople/mapping/dataexport/SurveyFormExporter.java
After upgrading poi, it is not possible to merge cells when there is only one item
No merging needed since only one question inside the group
NA
> [#3716] fix issue when the form has only one group

- GAE/src/org/waterforpeople/mapping/dataexport/SurveyFormExporter.java
crash stacktrace:
`java.lang.IllegalArgumentException: Merged region A838 must contain 2 or more cells
File "HSSFSheet.java", line 716, in org.apache.poi.hssf.usermodel/addMergedRegion
File "HSSFSheet.java", line 670, in org.apache.poi.hssf.usermodel/addMergedRegion
File "SurveyFormExporter.java", line 226, in org.waterforpeople.mapping.dataexport/writePaperSheet
File "SurveyFormExporter.java", line 159, in org.waterforpeople.mapping.dataexport/writeSurvey
File "SurveyFormExporter.java", line 96, in org.waterforpeople.mapping.dataexport/export
File "exporter.clj", line 75, in akvo.flow-services.exporter/export-report
(.export exporter criteria file base-url options)`
> [#3729] fixed crash related to merged cells

- scripts/Readme.md
- scripts/data/build.xml
so now we can call data/scripts using this approach
`cd akvo-flow/scripts/data`
`ant devRemoteAPI -Dservice=XXX -Dargs=XXX`
eg:
`ant devRemoteAPI -Dservice=AddUsers -Dargs=./dev_environment_users.csv`
> Adapt ant script to work locally with scripts/data 

- GAE/src/com/gallatinsystems/survey/dao/QuestionGroupDao.java
- GAE/src/com/gallatinsystems/survey/domain/QuestionGroup.java
- GAE/src/org/akvo/flow/api/export/SurveyRestServlet.java
- GAE/src/org/akvo/flow/xml/XmlQuestionGroup.java
- GAE/src/org/waterforpeople/mapping/app/util/DtoMarshaller.java
- GAE/src/org/waterforpeople/mapping/dataexport/service/BulkDataServiceClient.java
- GAE/test/org/akvo/flow/util/FlowJsonObjectWriterTests.java
- GAE/test/org/akvo/flow/xml/FlowXmlObjectWriterTests.java
- GAE/test/org/waterforpeople/mapping/dataexport/SurveyReplicationImporterTests.java
Question group translations were not copying across instances 
* Renamed the translations map for Question domain object to prevent conflict during calls of BeanUtils.copyProperties()
* Convert transation map in QuestionGroupDto to a TranslationDto map to enable correct parsing when received on the other end of the copying
* Surround parseQuestionGroups() logic with outer try-catch statement rather than having it within a for loop.
* More precise exceptions thrown and caught
* Add test cases for importer class
> [#3747] Copy question group translations across instances

- Dashboard/app/js/lib/views/surveys/question-view.js
- Dashboard/app/js/templates/navSurveys/question-view.handlebars
if the config mandatoryQuestionID is set to true, variable names are
mandatory, we don't allow saving a question if the variable name is empty
> [#3756] make variable names mandatory

- GAE/src/org/akvo/flow/xml/XmlForm.java
- GAE/src/org/waterforpeople/mapping/app/gwt/client/survey/SurveyDto.java
- GAE/src/org/waterforpeople/mapping/app/web/SurveyAssemblyServlet.java
- GAE/test/org/akvo/flow/xml/FlowXmlObjectWriterTests.java
we need a new way to validate bootstrap files for migrated instances
Add new field: alias to flow forms xmls
update tests
NA
> [#3770] added alias to form xmls

- GAE/src/org/akvo/flow/api/app/DataPointUtil.java
- GAE/src/org/akvo/flow/rest/handler/FormInstanceRequestHandler.java
- GAE/src/org/waterforpeople/mapping/dao/SurveyInstanceDAO.java
- GAE/test/com/gallatinsystems/surveyal/dao/SurveyInstanceDAOTest.java
- GAE/test/org/akvo/flow/api/app/DataStoreTestUtil.java
- GAE/test/org/akvo/flow/api/app/FormInstanceUtilTest.java
- GAE/test/org/akvo/flow/rest/handler/FormInstanceRequestHandlerTests.java
* When we delete a registration form instance, the corresponding datapoint in addition to all the other monitoring form instances, are deleted.
> [#3597] Registration form instance delete

- scripts/data/remove_orphaned_answers.sh
- scripts/data/src/org/akvo/gae/remoteapi/FixOrphanedQuestionAnswers.java
After fixing this issue https://github.com/akvo/akvo-flow/issues/3771 some question answers remained orphan and this made impossible to export geojson responses
Created this script to cleanup for one form, this script can then be reused if we have the same issue again
NA
> [#3771] added script to clean

- GAE/src/com/gallatinsystems/survey/dao/QuestionDao.java
- GAE/src/org/waterforpeople/mapping/app/web/rest/QuestionRestService.java
The instances that require a mandatory variable name have call to verify its uniqueness but we fetch all the questions for the form instead of just the ones with that variable name
> [#3796] optimize variable name verification

- Dashboard/app/js/lib/controllers/permissions.js
- Dashboard/app/js/templates/application/application.handlebars
The dialog appears but users can accept before knowing that monitoring instances will also be deleted
while loading:
when loading completed:
> [#3597] disable ok button while number of items is still loading

- Config/instanceConfigurator/src/org/akvo/flow/templates/appengine-web.xml.ftl
Related doc: https://cloud.google.com/appengine/docs/legacy/standard/java/config/appref#scaling_elements_automatic_scaling
The default max-concurrent-requests is too low and forcing more instances to spawn.
The default max instance is really high and incurring high costs.
Increase max-concurent-requests, lower max-instance
-----------
Related to akvo/akvo-flow-server-config#740
> Configure automatic scaling
