scripts/data/src/org/akvo/gae/remoteapi/DeleteData.java, scripts/data/src/org/akvo/gae/remoteapi/Process.java, scripts/data/src/org/akvo/gae/remoteapi/RemoteAPI.java
* The Process now has a DataStoreService parameter, that avoids making
that call on each implemetation
=> [#1082] Code improvements on RemoteAPI class

GAE/src/com/gallatinsystems/gis/map/MapUtils.java, GAE/src/org/waterforpeople/mapping/app/web/DataProcessorRestServlet.java, GAE/src/org/waterforpeople/mapping/app/web/TestHarnessServlet.java, GAE/src/org/waterforpeople/mapping/app/web/dto/DataProcessorRequest.java, GAE/src/org/waterforpeople/mapping/dao/SurveyInstanceDAO.java, GAE/src/org/waterforpeople/mapping/domain/SurveyInstance.java, GAE/war/WEB-INF/queue.xml
* Adds a new queue for updating summary counts
* Delete a `SurveyedLocale` when there are no more related survey instances
* Remove test harness call
=> [#730] Refactor delete survey instance functionality

GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyInstanceRestService.java
* Extract `surveyId` before deleting survey instance
=> [#1104] Refactor survey instance deletion

Dashboard/app/cljs/src/org/akvo/flow/dashboard/users/role_details.cljs, Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/lib/controllers/survey-selection.js, Dashboard/app/js/lib/controllers/user-controllers.js, Dashboard/app/js/lib/router/router.js, Dashboard/app/js/lib/views/views.js, Dashboard/app/js/templates/navData/data-cleaning.handlebars, GAE/src/com/gallatinsystems/user/domain/Permission.java
* Add data cleaning permission
* Reimplement folder filtering based on the new hierarchical folder structure views
=> [#943] Add `Data Cleaning` Permission

Dashboard/app/js/lib/views/reports/export-reports-views.js, GAE/src/org/waterforpeople/mapping/app/web/dto/DataBackoutRequest.java
* Don't send to/fromDate values in the request if they are not used
=> [#1103] Fix toDate parsing issue

GAE/src/org/waterforpeople/mapping/app/web/CurrentUserServlet.java
* For UI actions and elements (hiding, disabling) we need permissions sent to the UI.  This change gives superAdmin unrestricted access  on frontend elements
=> [#943] Allow superAdmin user complete access

GAE/src/org/waterforpeople/mapping/app/web/SurveyAssemblyServlet.java
* Read & format <application> entity from appengine-web.xml config file
=> [#1071] Add app property to form XML

GAE/src/com/gallatinsystems/common/Constants.java, GAE/src/com/gallatinsystems/common/util/S3Util.java, GAE/src/org/waterforpeople/mapping/app/web/ProcessorServlet.java, GAE/src/org/waterforpeople/mapping/app/web/TaskServlet.java, GAE/src/org/waterforpeople/mapping/app/web/dto/TaskRequest.java
* Cleaning up the exception handling parts of the data processing code, i.e. remove unnecessary exceptions
* Add rescheduling + retry mechanism
=> [#1185] Data file processing exception handling improvements

GAE/src/com/gallatinsystems/surveyal/domain/SurveyedLocale.java, GAE/src/org/waterforpeople/mapping/domain/SurveyInstance.java
* Truncate display name to 500 characters
=> [#1213] Truncate display name

scripts/data/src/org/akvo/gae/remoteapi/InstanceStats.java
* Produces the count of `SurveyInstance` and `SurveyedLocale`
=> [#1261] InstaceStats data script

GAE/src/org/waterforpeople/mapping/dao/SurveyInstanceDAO.java
* Persist the entities, then query the IDs
=> [#1247] Postpone 'Key' attribute retrieval (NPE)

GAE/src/com/gallatinsystems/survey/dao/SurveyUtils.java, GAE/src/org/waterforpeople/mapping/app/web/DataProcessorRestServlet.java, GAE/src/org/waterforpeople/mapping/app/web/dto/DataProcessorRequest.java, GAE/src/org/waterforpeople/mapping/app/web/rest/QuestionGroupRestService.java
* When copying surveys, handle copying of question groups in the same task, i.e. no additional tasks for each question group as was the case before.
* Handle dependency resolution for questions *only* for copying of surveys.
=> [#1217] Copy question group tasks

GAE/src/org/waterforpeople/mapping/app/web/TaskServlet.java
* Sequentially access datasotore for instance/locale saves.
=> [#1282] Synchronise datastore access

scripts/data/src/org/akvo/gae/remoteapi/AddUsers.java, scripts/data/src/org/akvo/gae/remoteapi/DataUtils.java
* Add users or update old roles in the datastore
=> [#1305] Data script to add users, update old roles

GAE/src/org/waterforpeople/mapping/dao/SurveyInstanceDAO.java
* Attempt to find the question, and proceed if found.
=> [#1307] Ensure questions are found in the DB

GAE/src/com/gallatinsystems/gis/map/MapUtils.java, GAE/src/com/gallatinsystems/surveyal/app/web/SurveyalRestServlet.java
* Ensure locale is deleted, regardless of geocells presence.
=> [#1329] Isolate locale deletion

Dashboard/app/css/library.scss, Dashboard/app/css/main.scss
I do not have any data on my dashboard locally, so I could not test this.
1) Go to data > inspect data tab
2) Select a form and find data submitted inside the form
3) Click edit.
4) Check that previous - delete - next menu is properly aligned.
=> [#1294] Fixed layout (blindly)

GAE/src/org/waterforpeople/mapping/app/web/SurveyedLocaleServlet.java
* Don't process SV w/o a valid questionID
* Simplify type assignment
=> [#1335] Skip invalid responses

Dashboard/app/js/lib/views/reports/report-views.js, Dashboard/app/js/templates/navReports/chart-reports.handlebars
#1004 
* Show number of responses along with percentage for Dashboard charts
* Add "Total: x answers" label for vbar and hbar charts
=> [#1004] show number with percentage for charts

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java, GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
* Add identifier and display name columns to non-monitoring data exports
* Add device identifier column to data exports
=> [#1204] Raw data report additions

Dashboard/app/css/users.scss
Fixes #1052 by adding a pointer cursor on hover to links in the Users tab
=> [#1052] add pointer cursor for user tab links

Dashboard/app/css/main.scss, Dashboard/app/js/templates/navData/inspect-data.handlebars
Fixes #1346 by moving inline styles from the Inspect Data tab to main.scss
=> [#1346] Move inline styles to main.scss

Dashboard/Assetfile, Dashboard/AssetfilePublic
Fixes #809 
The folder /admin/css/custom-theme/images was not being referenced correctly in the Dashboard Assetfiles. This PR adds that folder to Assetfile and AssetfilePublic
=> [#809] Fix minor UI regressions

GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
* Modify visibility of function to enable report validation
* Connected to this PR https://github.com/akvo/akvo-flow-services/pull/109
=> [#1205] Enable public access to datasheet of a report

Dashboard/app/js/templates/navSurveys/question-view.handlebars
=> [#1006] Specify Question ID is optional

Dashboard/app/css/main.scss
=> [#1376] remove icon_cal.png

Dashboard/app/js/templates/navData/cascade-resources.handlebars
=> [#1044] remove redundant cascade button

Dashboard/app/js/templates/navData/data-cleaning.handlebars
=> [#1126] Remove langauge menu from Data Cleaning tab

Dashboard/app/css/main.scss, Dashboard/app/js/templates/navDevices/devices-list-tab/devices-list.handlebars
=> [#1273] fix position of buttons on devices tab

Dashboard/app/css/main.scss, Dashboard/app/js/templates/navData/inspect-data.handlebars
=> [#1409] move date inputs to filter block

GAE/src/com/gallatinsystems/common/Constants.java, GAE/src/org/waterforpeople/mapping/app/web/RawDataRestServlet.java, GAE/src/org/waterforpeople/mapping/dao/QuestionAnswerStoreDao.java, GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java, GAE/src/org/waterforpeople/mapping/domain/SurveyInstance.java
* Create surveyed locales for new raw data report instances
=> [#1400] Import registration forms

Dashboard/app/js/templates/navData/inspect-data.handlebars, Dashboard/app/js/templates/navData/monitoring-data.handlebars
* Fix template error under the monitoring tab
* Render the responses under monitoring tab by question group
=> [#269] Fix monitoring tab template

Dashboard/app/js/lib/views/data/question-answer-view.js, Dashboard/app/js/templates/navData/inspect-data.handlebars, Dashboard/app/js/templates/navData/monitoring-data.handlebars
* Retored QuestionAnswerView to be previous state
* Using extended QuestionAnswerView class with specialised template to be used exclusively under the inspect data tab
=> [#269] Restore previous monitoring tab view

GAE/src/com/gallatinsystems/survey/dao/SurveyUtils.java
* Prevent timeouts by using backend instance to copy surveys
=> [#1417] Use backend instance to copy surveys

Dashboard/app/css/main.scss, Dashboard/app/js/templates/navReports/export-reports.handlebars
=> [#1484] Affix survey select menu to top of export reports tab

GAE/src/org/akvo/flow/events/EventUtils.java
* Add 'iteration' if it exists
* Look up the answer value using both 'value' and 'valueText'
=> [#1477] Enhance answerCreated and answerUpdated events

Dashboard/app/js/lib/views/views.js
* Format timestamp as correctly rendered data on maps
=> [#571] Render date response correctly on map

Dashboard/app/js/lib/controllers/data-controllers.js, Dashboard/app/js/lib/models/FLOWrest-adapter-v2-common.js, Dashboard/app/js/lib/views/data/inspect-data-table-views.js
* Refactor use of `since` cursor variable while navigating pages
=> [#1125] Fix previous button on inspect data tab

Dashboard/app/js/lib/controllers/data-controllers.js, Dashboard/app/js/lib/models/FLOWrest-adapter-v2-common.js, Dashboard/app/js/lib/views/data/inspect-data-table-views.js, Dashboard/app/js/lib/views/data/monitoring-data-table-view.js, Dashboard/app/js/templates/navData/inspect-data.handlebars, Dashboard/app/js/templates/navData/monitoring-data.handlebars
* Refactored the handling of the `since` cursor
* Refactored the numbering of items in the data point list
=> [#1299] Fix next button on monitoring tab

Dashboard/app/js/lib/controllers/permissions.js, Dashboard/app/js/lib/controllers/user-controllers.js, Dashboard/app/js/lib/views/surveys/form-view.js, Dashboard/app/js/lib/views/surveys/question-view.js, Dashboard/app/js/lib/views/surveys/survey-details-views.js, Dashboard/app/js/lib/views/surveys/survey-group-views.js, Dashboard/app/js/templates/navSurveys/edit-questions.handlebars, Dashboard/app/js/templates/navSurveys/form.handlebars, Dashboard/app/js/templates/navSurveys/project-list.handlebars, Dashboard/app/js/templates/navSurveys/question-view.handlebars
* Implement UI changes regarding read only permissions
=> [#1124]  Read only permissions

Dashboard/app/css/main.scss
=> [#1125] Fix next and previous buttons css

Dashboard/app/js/templates/navSurveys/project-list.handlebars, Dashboard/app/js/templates/navSurveys/project.handlebars
* Hide new form tab item for read only
* Hide folder move icon for read only
=> [#1124] Add new form tab hide

Dashboard/app/js/lib/views/views-public.js, Dashboard/app/js/lib/views/views.js
=> [#1462] Modify tooltip helper to replace escape char with entity

GAE/src/org/akvo/flow/domain/DataUtils.java, GAE/src/org/waterforpeople/mapping/app/web/DataBackoutServlet.java, GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
* Only include the *signed by* section in the export
* Ignore signature question values during report import
=> [#1453] Signature questions report generation

GAE/src/org/waterforpeople/mapping/app/web/DeviceNotificationRestServlet.java, GAE/src/org/waterforpeople/mapping/app/web/SurveyManagerServlet.java, GAE/src/org/waterforpeople/mapping/app/web/dto/SurveyManagerRequest.java
* Update the last contact date when the device downloads forms or accesses the `/devicenotification` url
=> [#1585] Update device last contact date with dashboard

Dashboard/app/js/lib/views/maps/map-views-common.js
=> Parse response from a geotagged photo question on cartodb maps

GAE/src/org/waterforpeople/mapping/app/gwt/server/survey/SurveyServiceImpl.java
* Assume registration form on non-monitored surveys
* Check newLocaleSurveyId on monitored ones
=> [#1611] Prevent NPE on non-monitored surveys

Dashboard/app/cljs/src/org/akvo/flow/dashboard/t.clj
* Do not use local storage for language configuration when loading user tab
=> [#1602] Users tab loading

GAE/src/com/gallatinsystems/device/dao/DeviceDAO.java, GAE/src/org/waterforpeople/mapping/app/web/DeviceNotificationRestServlet.java, GAE/src/org/waterforpeople/mapping/app/web/LocationBeaconServlet.java, GAE/src/org/waterforpeople/mapping/app/web/SurveyManagerServlet.java
* Small refactor on device data update
* Only update, not register devices on DeviceNotificationRestServlet
=> [#1644] Avoid multiple registration for devices

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Integers were shown with a trailing decimal point.
=> [#923]Numbers formatted with 0.### looked bad in Excel. 

Dashboard/app/js/lib/router/router.js
* This fixes a regression that causes question properties not to be loaded.
=> [#987] Load metrics when loading surveys

Dashboard/app/js/lib/views/surveys/survey-group-views.js
* This has to be fixed as refactor of overall state management strategy for dashboard.
=> [#1402] Roll back blank page fix.

Dashboard/app/css/main.scss, Dashboard/app/js/templates/navData/monitoring-data.handlebars
=> [#1703] Set menu container to fill row

RELEASE_NOTES.md
=> [#1739] Fix release notes writing

GAE/src/com/gallatinsystems/survey/dao/DeviceSurveyJobQueueDAO.java
This should help with most of the ghost survey assignments
=> [#1741]Do not try to match an empty devicePhoneNo to a legacy assignment

Dashboard/app/css/main.scss, Dashboard/app/js/templates/application/application-public.handlebars
=> [#1640] Remove scrolling on flow public page

GAE/src/org/waterforpeople/mapping/app/gwt/client/device/DeviceDto.java, GAE/src/org/waterforpeople/mapping/app/web/rest/DeviceRestService.java
* Eliminate the use of redundant property copying
=> [#1803] Timeout while retrieving devices list (connect #1803)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Lets exporter survive missing cascade reosurces
=> [#1795]Handle missing cascade resource. (Connect #1795)

Dashboard/app/js/templates/application/footer-public.handlebars, Dashboard/app/js/templates/application/footer.handlebars
=> Issue/1815 update copyright year (connect #1815)

Dashboard/app/js/lib/controllers/data-controllers.js, Dashboard/app/js/lib/views/data/monitoring-data-table-view.js
Fix the null object issues reported in #1820
=> [#1820] Add guard to prevent js null object error (connect #1820)

GAE/src/com/gallatinsystems/diagnostics/app/web/RemoteExceptionRestServlet.java, GAE/src/com/gallatinsystems/diagnostics/app/web/dto/RemoteExceptionRequest.java, GAE/src/com/gallatinsystems/diagnostics/domain/RemoteStacktrace.java
See #1823
Removed the check for phoneNumber parameter
Added storing of androidId parameter
Gave a simpleDateFormat constructor a locale parameter
=> Issue/1823 allow stacktraces without phonenumber (Connect #1823)

GAE/src/com/gallatinsystems/device/dao/DeviceDAO.java, GAE/src/org/waterforpeople/mapping/app/web/DeviceNotificationRestServlet.java
=> Issue/1819 save received app version (Connect #1819)

Dashboard/Gemfile.lock, Dashboard/app/js/lib/views/maps/map-views-common.js, Dashboard/app/js/lib/views/views.js
=> [#1800] carto maps render caddisfly results (connects #1800)

Dashboard/Gemfile.lock, Dashboard/app/js/lib/views/maps/map-views-common.js
=> [#1744] Carto maps change geoshape hide/show link position to below map (connect #1744)

scripts/data/src/org/akvo/gae/remoteapi/UserList.java
* Enable the user list generation data script to use service accounts.
=> [#1888] Refactor `UserList` generation script to use service accounts (connects #1888)

GAE/src/resources/caddisfly/caddisfly-tests.json
2 sensors missing 
Added the following sensors:
soil electrical conductivity
soil moisture
Have been tested and displays correctly in the dashboard survey creation and in the app. Since I do not have a recent version of the Caddisfly app yet I have not tested collecting any actual data yet.
NA
=> Added 2 new Caddisfly sensors (connect #1863)

Dashboard/app/css/main.scss, Dashboard/app/js/lib/views/maps/map-views-common-public.js, Dashboard/app/js/lib/views/views-public.js, Dashboard/app/js/lib/views/views.js, Dashboard/app/js/templates/navMaps/nav-maps-common.handlebars
=> [#1903] caddisfly results public map (connect #1903)

Dashboard/app/js/templates/navSurveys/manage-translations.handlebars, Dashboard/app/js/templates/navSurveys/project.handlebars
Check that it’s gone from survey overview and gone from survey
translation
=> [#1861] Removed survey description (connect #1861)

GAE/src/org/waterforpeople/mapping/domain/CaddisflyResource.java, GAE/src/org/waterforpeople/mapping/domain/CaddisflyResult.java, GAE/src/resources/caddisfly/caddisfly-tests.json
We have to add sensors one by one by hand
Now it will be possible to just paste the contents from the caddisfly app json to caddisfly-tests.json and they will start showing in the dashboard
=> Paste caddisfly sensors (connect #1915)

Dashboard/app/js/lib/controllers/data-controllers.js, Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/lib/views/surveys/question-view.js, Dashboard/app/js/templates/navSurveys/question-view.handlebars, GAE/src/com/gallatinsystems/survey/dao/CaddisflyResourceDao.java
The caddisfly test definitions were being loaded by converting a file to a string and then parsing it.  Also in the UI app, the resources were loaded using a controller object whereas loading the resources using a controller class take advantage of some of the automated loading features from ember
=> [#1918] Refactor caddisfly test definitions loading (connect #1918)

Dashboard/app/js/lib/controllers/data-controllers.js
* Caddisfly tests were not sorted in alphabetical order in the question definition part of the dashboard.
=> [#1916] Arrange caddisfly tests in alphabetical order (connect #1916)

GAE/src/resources/caddisfly/caddisfly-tests.json
* We now add the new caddisfly tests to the list of available ones
* Prefixes have been added to the test names to distinguish between water and soil tests
=> Update caddisfly test definitions (connect #1915)

GAE/src/resources/caddisfly/caddisfly-tests.json
Phosphate Hach test has been added back to caddisfly
Copy pasting the tests file once again.
=> Copied all tests from caddisfly assets (connect #1894)

GAE/src/com/gallatinsystems/common/Constants.java, GAE/src/org/waterforpeople/mapping/app/web/BootstrapGeneratorServlet.java, GAE/src/org/waterforpeople/mapping/app/web/SurveyAssemblyServlet.java
the form xml file is generated without surveyId inside the file which not ocnvenient for the mobile device who has to get the surveyId from the folder name.
- added surveyId field inside the form xml file
- removing invalid chars from the bootstrap survey file
NA
=> SurveyId in form xml file (connect #1927)

GAE/src/com/gallatinsystems/user/domain/User.java, GAE/src/org/waterforpeople/mapping/app/web/rest/UserRestService.java, GAE/src/org/waterforpeople/mapping/app/web/rest/security/GoogleAccountsAuthenticationProvider.java
=> Check for empty `superAdmin` property on user entity (connect #1959)

GAE/src/com/gallatinsystems/framework/dao/BaseDAO.java, GAE/src/com/gallatinsystems/survey/dao/SurveyDAO.java, GAE/src/com/gallatinsystems/survey/dao/SurveyGroupDAO.java, GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyRestService.java
- Accepts `userId` as parameter
- Uses generics to avoid raw types
=> [#1970] Refactor BaseDAO (connect #1970)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java, GAE/src/org/waterforpeople/mapping/dataexport/SurveySummaryExporter.java
a. Strip the Json from the answers when they are inserted into the rollup list
b. Test with the same sheet name that we will use to create if it does not exist.
=> [#1968]Extract JSON content; test the same name that would be created (Connect #1968)

Dashboard/app/css/main.scss, Dashboard/app/js/templates/navSurveys/edit-questions.handlebars, Dashboard/app/js/templates/navSurveys/question-view.handlebars
=> Click on question and group names to toggle edit mode (connect #1831)

Dashboard/app/js/lib/controllers/maps-controllers-common.js, GAE/src/org/waterforpeople/mapping/app/web/EnvServlet.java
We remove an element `countries` that is no longer used but is still included in the request for environment variable loaded when loading the dashboard.
=> Remove `countries` element from flowenv object (connect #498)

GAE/war/Env.vm
Still tried to load the deleted controller
Stop that
=> [#498]Do not try loading deleted controller. (connect #498)

RELEASE_NOTES.md
=> [connect #2005] Added release notes for v1.9.15.

RELEASE_NOTES.md
Ensure release numbers are displayed correctly in GitHub (stricter MD handling).
Corrected MD format for more recent section headings.
Corrected spacing for consistency.
=> [connect #2005] Corrected Markdown formatting and layout.

GAE/src/com/gallatinsystems/framework/rest/AbstractRestApiServlet.java, GAE/src/org/waterforpeople/mapping/app/web/DataApprovalServlet.java, GAE/src/org/waterforpeople/mapping/app/web/dto/DataApprovalRequest.java, GAE/src/org/waterforpeople/mapping/app/web/dto/DataApprovalRestResponse.java, GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java, GAE/src/org/waterforpeople/mapping/dataexport/service/BulkDataServiceClient.java, GAE/war/WEB-INF/web.xml
* For data approval reports, we need to include the latest approval status along with the title of the step in that status.
* This PR creates the necessary servlet and data transfer objects to enable the retrieval of the data approval entities (steps and statuses).  In this first part we only retrieve the approval steps for a given survey if data approval has been enabled.
=> Retrieve data approval steps for reports (connect #1666)

GAE/src/org/waterforpeople/mapping/app/web/SurveyRestServlet.java
=> Fix logger class for SurveyRestServlet (connect #555)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
* When checking for whether a `SurveyGroup` entity has data approval set, we check whether we have the entity first
=> Add check for null `SurveyGroup` entity (connect #1666)

GAE/src/org/waterforpeople/mapping/dataexport/SurveySummaryExporter.java, GAE/src/org/waterforpeople/mapping/dataexport/service/BulkDataServiceClient.java
* We parse the `type` property of a JSON response for question details, in order to be able to generate the raw data reports
=> Parse question type (connect #1442)

GAE/src/org/waterforpeople/mapping/dataexport/service/BulkDataServiceClient.java
* Some imports seem to have been used at the beginning and in the middle of the file.  We remove the duplicates with this PR
=> Remove duplicated imports (connect #555)

.gitignore
NA
Added inttellij files to .gitignore
NA
=> Added intellij files and folders to .gitignore (connect # 2040)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
If the Boolean property was null, you would throw a NPE 
Check for that
=> [#2047]Protect against null. (Connect #2047)

Dashboard/app/css/main.scss, Dashboard/app/js/templates/navMessages/nav-messages.handlebars
Added also white space to remove on messages list
=> [#2062][#1972] Fix breadcrumb appearing on top of message

Dashboard/app/css/main.scss
This was only appearing on published surveys
=> [#2065] Remove survey icon (connect #2065)

Dashboard/app/css/main.scss
=> [#2069] Fixed truncated edit and delete (connect #2069)

GAE/src/com/gallatinsystems/framework/dao/BaseDAO.java
=> [#2092] Disable data filtering for superAdmin users (connect #2092)

GAE/src/org/waterforpeople/mapping/app/web/rest/QuestionRestService.java
Marshalled Question data the old, slow way
Switch to the faster way from beanutils
=> [#2088]Use beanutils copying everywhere. (Connect #2088)

Dashboard/app/js/lib/models/models.js, Dashboard/app/js/lib/views/surveys/survey-details-views.js, GAE/src/com/gallatinsystems/survey/domain/QuestionGroup.java, GAE/src/org/akvo/flow/domain/mapper/QuestionDtoMappableFields.java, GAE/src/org/akvo/flow/domain/mapper/QuestionDtoMapper.java, GAE/src/org/akvo/flow/domain/mapper/QuestionGroupDtoMapper.java, GAE/src/org/akvo/flow/domain/mapper/QuestionOptionDtoMapper.java, GAE/src/org/waterforpeople/mapping/app/gwt/client/survey/QuestionGroupDto.java, GAE/src/org/waterforpeople/mapping/app/gwt/client/survey/QuestionGroupDtoMapper.java, GAE/src/org/waterforpeople/mapping/app/web/SurveyRestServlet.java, GAE/src/org/waterforpeople/mapping/app/web/rest/QuestionGroupRestService.java, GAE/src/org/waterforpeople/mapping/app/web/rest/QuestionRestService.java, GAE/src/org/waterforpeople/mapping/dataexport/service/BulkDataServiceClient.java
Uses slow DtoMarshaller code.
desc/description fields are not used.
Switch to beanutils copying.
Remove the field.
=> Issue/2089 speed up questiongroup creation (Connect #2089)

GAE/src/com/gallatinsystems/survey/dao/QuestionDao.java, GAE/src/org/waterforpeople/mapping/dataexport/SurveySummaryExporter.java
If a question had an inconsistent surveyId pointer, an NPE would be thrown.
check for it and avoid trying to sort those questions.
=> [#2096]Protect against inconsistent question->survey references. (Connect #2096)

scripts/data/check-survey-structure.sh, scripts/data/src/org/akvo/gae/remoteapi/CheckSurveyStructure.java
db messed up
scan and optionally fix errors in survey structure (Question groups, questions and options)
=> Issue/2098 check survey structure (Connect #2098)

GAE/src/org/waterforpeople/mapping/analytics/dao/SurveyQuestionSummaryDao.java
NPEs were frequently reported here:
```
java.lang.NullPointerException  at org.waterforpeople.mapping.domain.SurveyInstance.updateSummaryCounts(SurveyInstance.java:396)
at org.waterforpeople.mapping.dao.SurveyInstanceDAO.save(SurveyInstanceDAO.java:159)
at org.waterforpeople.mapping.app.web.TaskServlet.processFile(TaskServlet.java:204)
at org.waterforpeople.mapping.app.web.TaskServlet.ingestFile(TaskServlet.java:388) 
```
Ensure caching code never returns a null pointer in the result list
=> Issue/2107 npe in summary counts (Connect #2107)

Dashboard/app/dashboard.html, Dashboard/app/public.html
Some JavaScript files were served from Flow
Changed the source of files to available CDNs
=> Serve js files from available CDNs (connect #1688)

scripts/data/src/org/akvo/gae/remoteapi/CheckSurveyStructure.java
Version that was checked in of the structure fix script has a silly bug.
Use the right flags in the right places.
=> [#2165]Swap flags tested. (Connect #2165)

GAE/src/org/waterforpeople/mapping/app/gwt/client/survey/SurveyService.java, GAE/src/org/waterforpeople/mapping/app/gwt/server/survey/SurveyServiceImpl.java
=>  Code cleanup - remove unused methods (connect #555)

README.md
=> [2171] Added a thank you to BrowserStack

Dashboard/app/js/lib/views/views.js, Dashboard/app/js/templates/application/navigation.handlebars, GAE/src/org/waterforpeople/mapping/app/web/EnvServlet.java, GAE/war/Env.vm
* Maps are shown on the dashboard UI by default. However, some partners would like to be able to hide this button because of data visibility.
* We are creating the possibility to in some cases hide the maps button by setting an environment variable `showMapsTab`
=> Implement show/hide maps feature flag (connect #2153)

GAE/war/WEB-INF/rest-servlet.xml
* Spring beans are created at application startup time with the consequence that the application startup time is longer.
* We configure the beans to only be initialised when they are needed.
=> Configure spring to initialize beans lazily (connect #2179)

scripts/data/delete_data.sh, scripts/data/src/org/akvo/gae/remoteapi/DeleteData.java
* Added a shell script to kick off execution
* Filter the `SurveyedLocale` entities by `surveyGroupId` property
=> Data deletion script improvements (connect #2190)

scripts/data/src/org/akvo/gae/remoteapi/HidePrivateSurveyData.java
The HidePrivateSurveyData script can fail when the number of entites is very large.
Save in batch mode
=> [#2185]Save entities in batch mode. (Connect 2185)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java, GAE/src/org/waterforpeople/mapping/domain/QuestionAnswerStore.java, scripts/data/public_private_instance_count.sh
Display names in the raw data report don't change when the selection of questions change.
Build the display name during report generation and ignore any stored value.
=> Issue/2160 compose display name during report generation (Connect #2160)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Questionless questions made report generator crash.
Test for it.
=> [#1779]Survive optionless questions. (connect #1779)

GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyAssignmentRestService.java
Old, slow marshaling code
Beanutils
=> Issue/2035 speed up device tab (Connect #2035)

GAE/src/org/waterforpeople/mapping/app/web/rest/DeviceGroupRestService.java
dtoMarshaler is slow
Beanutils
=> Issue/2199 speed up devicegroup list (Connect #2199)

Dashboard/app/css/main.scss, GAE/src/org/waterforpeople/mapping/app/web/SurveyInstanceServlet.java, GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
No displaynames show up in reports for monitoring surveys.
Assemble them on-demand in the backend.
=> Issue/2160 assemble displaynames on demand in backend (Connect #2160)

GAE/src/org/akvo/flow/domain/DataUtils.java, GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Cascade JSON answers caused inifinite sheetname-testing loops
Keep number suffix in the first 31 chars; stop after 1000 tries.
=> Issue/2206 make unique export sheet names (Connect #2206)

scripts/data/add_dev_environment_users.sh, scripts/data/add_users.sh, scripts/data/dev_environment_users.csv
* Add shell scripts to be able to run user addition data script both on remote and local dev servers
=> Adding user addition shell scripts and test data (connect #2193)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Generating reports would crash when caddisfly questions had null fields.
Check for that.
=> Issue/2216 npe in caddisflyheader (Connect #2216)

GAE/src/org/waterforpeople/mapping/app/web/SurveyInstanceServlet.java
SurveyInstances with no associated SurveyedLocale cannot be fetched; 500 is returned.
Avoid the NPE
=> [#2211]Protect against nulls. (Connect #2211)

GAE/src/org/waterforpeople/mapping/app/web/SurveyedLocaleServlet.java
When lots of forms in one survey, datapoint sync still timeouts
Reduce the number of results to 30
NA
=> Reduced datapoint sync batch to 30 items (connect #2238)

GAE/src/com/gallatinsystems/survey/dao/CaddisflyResourceDao.java
* Retrieve caddisfly tests file for exports
=> [#1825] Retrieve caddisfly tests for generating export reports

GAE/src/org/waterforpeople/mapping/app/web/SurveyedLocaleServlet.java
Crash when there are no surveyalValues for that surveyedLocale
added null checks and some annotations
NA
=> Fixed NPE in SurveyedLocaleServlet

Dashboard/app/css/main.scss
Folder name
Survey name
Group name
question name
=> [#1996] Unified colors and hover (connect #1996)

Dashboard/app/js/templates/navSurveys/question-view.handlebars
Question checkboxes were shown on one line, not one above each other as before.
Put them in a list.
=> [#1922] Checkboxes appears as lists. (Connect #1922)

Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/lib/core-common.js
User could move a folder into itself.
Disable selecting the folder being moved.
=> [#1367]Do not open folder being moved. Fix spelling. (Connect #1367)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Too weird report structure for RQGs for most consumers.
Add the survey metadata to all the repeat rows it applies to.
=> [#2247]Loop over more items. (Connect #2247)

Dashboard/app/js/templates/navSurveys/preview-view.handlebars
Remove the link to the documentation in the form preview for cascade type questions
=> Removed the link to documentation in form preview (connect  #2258)

Dashboard/app/js/templates/navDevices/devices-list-tab/devices-list.handlebars
Phone number column was present under Devices list
Deleted the phone number table rows from the Devices table in devices-list.handlebars
=> Remove phone number from devices list (connect #2299)

Dashboard/app/cljs/src/org/akvo/flow/dashboard/users/core.cljs, Dashboard/app/dashboard.html
find all places on the Flow web interface where the word "dashboard" is user visible, and then change it to the new word or even remove it if not needed.
removed the word "dashboard" from  the browser tab heading for Chrome
=> Change the word "dashboard" (connect #1842)

Dashboard/app/js/lib/controllers/maps-controllers-common.js, Dashboard/app/js/lib/models/models.js, Dashboard/app/js/lib/views/maps/map-views-common-public.js, Dashboard/app/js/lib/views/maps/map-views-common.js, Dashboard/app/js/lib/views/views-public.js, Dashboard/app/js/lib/views/views.js, Dashboard/app/js/templates/navMaps/nav-maps-common.handlebars
There was a lot of superfluous that could be replaced by already existing code
Replaced this code with reusable existing solutions
=> Maps code refactor (connect #2144)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Feature flags were set wrong for DATA_ANALYSIS report. (Copy-paste mistake.)
=> [#2278]Fix options for DATA_ANALYSIS report. (Connect #2278)

Dashboard/app/js/lib/views/reports/export-reports-views.js
=> [#2344]Move reportMode to opts.

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
=> [#2328]Add data sorting on collection date. (Connect #2238)

Dashboard/app/js/templates/navData/data-cleaning.handlebars
* The report generation action was renamed in a refactor but not changed under the data cleaning tab
* Fix the report generation action on the data cleaning
=> Use the renamed data cleaning report download action (connect #2282)

GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
=> Revert changes that made clojure import not work. (connect #2278)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Comprehensive report was broken; all raw data was on the first line
=> Use sheet method to track last-line-written everywhere. (Connect #2344)

GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
Missed that verify() was called from Clojure.
Teach it to parse new "group" headers.
=> Issue/2278 split rqgs into separate sheets (Connect #2278)

GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
Single-sheet imports were not designating the columns right.
=> [#2278]Update column predicates to handle single-sheet imports.

GAE/src/org/waterforpeople/mapping/dataexport/InstanceData.java, GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
Four empty geodata cells counted as a response during import.
=> Issue/2278 split rqgs into separate sheets (Connect #2278) 

GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
=> Issue/2278 split rqgs into separate sheets (Connect #2278, #2295)

Config/instanceConfigurator/src/org/akvo/flow/InstanceConfigurator.java, Config/instanceConfigurator/src/org/akvo/flow/templates/survey.properties.ftl
instanceUrl displayed in the mobile app, needs to be added manually
Add the new config and update template
=> Added new config setting and updated template (connect #2219) 

GAE/src/com/gallatinsystems/surveyal/app/web/SurveyalRestServlet.java, GAE/src/com/gallatinsystems/surveyal/domain/SurveyalValue.java, GAE/src/com/gallatinsystems/surveyal/domain/SurveyedLocale.java, GAE/src/org/waterforpeople/mapping/app/gwt/client/surveyinstance/SurveyInstanceDto.java, GAE/src/org/waterforpeople/mapping/app/web/RawDataRestServlet.java, GAE/src/org/waterforpeople/mapping/domain/SurveyInstance.java
Legacy fields cluttering the db
remove them
=> Remove sublevels and approximateLocation fields. (connect #2379)

GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
Cannot import new data on the data cleaning report sheets.
Enable that by having a special temp identifier pattern.
=> Import new data from split sheets (Connect #2368) 

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Headers in analysis report should be unique.
Make them unique, and clean up the header generation code.
=> First stage of unique headers (Connect #2315)

Dashboard/app/js/lib/controllers/maps-controllers-common.js, Dashboard/app/js/lib/views/maps/map-views-common-public.js, Dashboard/app/js/lib/views/maps/map-views-common.js, Dashboard/app/js/lib/views/views.js
A new instance of arrayController class was being created
Extend the arrayController class so no new instance is created
=> Use extend instead of create the arrayController for mapsController (connect #2275)

Dashboard/app/css/main.scss
Two obvious typos in main.scss
Fix them.
=> [#2198]Fix misspellings. (Connect #2198)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java, GAE/src/org/waterforpeople/mapping/dataexport/RawDataExporter.java, GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
Geocode unused
Ignore on input, do not output
=> [#2367]Hide and discard geocode on export and import. (Connect #2367)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Broken files were generated when >100 lines were output on the summary sheet for one question.
Do not output frequency table for NUMBER questions, make sure that we never go back up outside the file window (100 lines).
=> Issue/2279 error opening comprehensive in excel (Connect #2279)

Dashboard/app/js/templates/application/footer-public.handlebars, Dashboard/app/js/templates/application/footer.handlebars
In the footer we show the copyright with the years 2012-2017. We need to update to 2018
we updated to 2018
=> Replaced copyright from 2017 to 2018(connect #2429)

Dashboard/app/js/templates/navData/inspect-data.handlebars, Dashboard/app/js/templates/navData/monitoring-data.handlebars, Dashboard/app/js/templates/navSurveys/preview-view.handlebars
Style name in css file was fixed, but not the references to it
Update name everywhere
=> [#2385]Fix typo everywhere. (Connect #2385)

GAE/src/com/gallatinsystems/common/util/JFreechartChartUtil.java, GAE/src/org/akvo/AkvoColours.java, GAE/src/org/akvo/flow/util/JFreechartChartUtil.java, GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Comprehensive charts were pie diagrams.
Change them to bar graphs, style them according to Akvo brand book.
=> Issue/2428 comprehensive graph (Connect #2428)

Dashboard/app/js/lib/controllers/survey-controllers.js
Form version number was not getting updated after changing form name
Update status when saving form name change so that version number change is triggered
=> Update form version when saving a form name change (connect #1403)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
No graphs or counts for cascade questions
Treat them as option questions
=> [#2427]Handle cascade as option. (Connect #2427)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Chart summary was generated for all cascade levels.
Ignore lower levels.
=> [#2427]Only summarize leaf node. Clean up TODO comments. (Connect #2427)

GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
We supported a legacy format for data cleaning.
Simplify code by dropping that support. Generate an appropriate error message instead.
=> [#2330]Drop support for legacy format. (Connect #2330)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
The raw-data sheet of the comprehensive report was formatted like the data cleaning report.
Format it like the data analysis report instead.
=> [#2469]Make comprehensive report raw-data sheet have analysis format. (Connect #2469)

scripts/data/check_options.sh, scripts/data/src/org/akvo/gae/remoteapi/CheckOptions.java
Data script for checking old option data was too simple. Shell script was not the working version. 
Update to what I actually used.
=> [#2290]Count more things. Fix shellscript wrapper. (Connect #2290)

scripts/data/src/org/akvo/gae/remoteapi/CheckSurveyStructure.java
Data script could crash on bad db fields.
Test for null.
=> [#2508]Test for null survey pointer. (Connect #2508)

Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/lib/views/surveys/survey-group-views.js
Sometimes when a user selected a survey under the survey page, they would get a blank screen
Strict checking if survey is selected first before loading on survey page
=> Fix occasional blank screen on surveys tab (connect #1402)

Dashboard/app/js/lib/views/surveys/question-view.js
Correct variable name validation error message not always displayed
Display correct validation error message
=> Display correct variable name validation error message (connect #2474)

scripts/data/check-datapoint-location.sh, scripts/data/src/org/akvo/gae/remoteapi/CheckDataPointLocation.java
Some datapoints have their location wrong
Fix datapoint location using answer from the GEO question
NA
=> Script to fix datapoint location (connect #2520)

GAE/src/com/gallatinsystems/framework/dao/BaseDAO.java, GAE/src/org/waterforpeople/mapping/app/web/CurrentUserServlet.java
We had no idea who created/changed an entity, just when
Remember that
=> Issue/2525 log who changed entity(Connect #2525)

GAE/src/org/waterforpeople/mapping/dao/SurveyInstanceDAO.java
Since we changed the format of the IMAGE value, bad flenames have been entered into the DeviceFileJobQueue.
Extract the filename using an objectMapper.
=> [#2539]Extract filename from JSON object. Update copyright year. (Connect #2539)

Dashboard/app/js/lib/views/surveys/question-view.js
if a special character is inserted before variable name validation completes and the validation succeeds, saving question is allowed
check for special characters once more after variable name validation success
=> Check for special characters after variableName validation success (connect #2563)

GAE/src/com/gallatinsystems/framework/dao/BaseDAO.java
which should also not interfere w a user saving their own User entity. (Which was messing with locale setting.)
When a user changed their own User datastore entity it failed silently.
Saving to the datastore was also slow.
Get the userId in a better way.
=> [#2572]Faster way of getting userId, (Connect #2572)

GAE/src/com/gallatinsystems/framework/dao/BaseDAO.java
Some endpoints do not use GAE credentials. They were returned as an empty string, for some reason.
Store them as user 0.
=> [#2572]Handle unidentified users. (Connect #2572)

GAE/src/org/waterforpeople/mapping/app/web/CronCommanderServlet.java, GAE/src/org/waterforpeople/mapping/app/web/DeleteObjectTaskServlet.java, GAE/src/org/waterforpeople/mapping/app/web/SurveyTaskServlet.java, GAE/src/org/waterforpeople/mapping/app/web/dto/SurveyTaskRequest.java, GAE/war/WEB-INF/cron.xml
Entries stayed in the DFJQ forever
Check them once a week, delete those fulfilled or >2 years old.
=> Issue/2550 clean dfjq regularly (Connect #2550)

Dashboard/app/js/lib/views/views.js
Since the ember version we're currently on doesn't support radio buttons, a custom implementation had been set up but was not ideal and was unused
Improve on this implementation.
=> Improve custom implementation of Ember.RadioButton (connect #2578)

GAE/war/WEB-INF/cron.xml
Bad syntax for weekly scan.
Read The Fine Manual and fixed.
=> [#2550]Fix weekly syntax. (Connect #2550)

GAE/pom.xml
=> Build for java7 environment (connect #2406)

Dashboard/app/js/lib/views/views.js
A new implementation of Ember.Radio had broken how question options are displayed on survey preview
Reverting to previous implementation to fix this
=> Revert to previous Ember.Radio implementation (connect #2578)

scripts/deploy/deploy.sh, scripts/deploy/run.sh
- Run `:delegated` mount to speed things up in MacOS
https://docs.docker.com/docker-for-mac/osxfs-caching/
- Use `-z` to check for existing `GH_USER` and `GH_TOKEN` variables
=> [#2562] Small fixes in deployment scripts (connect #2562)

GAE/pom.xml
* Exclude certain files from the final war
=> Exclude unneeded files from the final war (connect #2624)

.travis.yml
=> [#2635] removing maven resolver-status files before travis cacheing

Dockerfile
=> [#2628] Upgrade curl (connect #2628)

Dashboard/app/js/templates/navData/data-cleaning.handlebars
There was an option to export report in the data cleaning tab which can already be done in the export reports tab
Removed export option from data cleaning
=> Remove report export from data cleaning (connect #2548)

GAE/pom.xml, GAE/war/WEB-INF/webapp-security.xml
* Upgrade to the most recent 3.2.x version of each library
=> [#2641] Upgrade Spring and Spring Security (connect #2641)

GAE/src/org/waterforpeople/mapping/app/web/rest/PlacemarkRestService.java
* Refactored the placemarks listing endpoint to cleanup and code and make it a little more clear
=> Refactor placemarks listing code (connect #2661)

GAE/pom.xml
=> Use maven repos over https (connect #2665)

Dashboard/app/js/lib/controllers/permissions.js, Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/lib/router/router.js, Dashboard/app/js/templates/application/navigation.handlebars, Dashboard/app/js/templates/navData/data-subnav.handlebars, Dashboard/app/js/templates/navData/inspect-data.handlebars, Dashboard/app/js/templates/navReports/chart-reports.handlebars, Dashboard/app/js/templates/navReports/export-reports.handlebars
Data viewing parts of the dashboard were being loaded even when the user did not have read permissions
Hide elements unless the data read permission is set
=> Load data viewing elements based on permissions set (connect #1558)

Dashboard/app/js/templates/application/navigation.handlebars, Dockerfile
Devices tab not loading because view is loaded after permissions are checked
Load view first then check permissions to display the link
=> Restore devices tab (connect #1558)

Dashboard/app/js/lib/controllers/maps-controllers-common.js, Dashboard/app/js/lib/models/models-public.js, Dashboard/app/js/lib/views/maps/map-views-common-public.js, Dashboard/app/js/lib/views/maps/map-views-common.js, Dashboard/app/js/templates/navMaps/nav-maps-common.handlebars, GAE/src/org/waterforpeople/mapping/app/web/rest/PlacemarkRestService.java, GAE/src/org/waterforpeople/mapping/app/web/rest/dto/PlacemarkDto.java
* All data points were loaded in the map when it was selected
* We only load the map and the survey selection filter. Loading the datapoints is done based on what the user selects.
=> UI changes to filter datapoints based on the `surveyId`

scripts/data/delete_users.sh, scripts/data/src/org/akvo/gae/remoteapi/DeleteUsers.java
Need to delete lots of old superAdmin users, because they have quit. Also, GDPR.
Make a data script. It has been run on all live instances, removing all superAdmins not belonging to the Flow development team.
=> Issue/2613 data script for deleting users (Connect #2613)

GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
If a column/question # in the import file did not exist in the current survey, an NPE was thrown.
Test for it
=> [#2568]Prevent NPEs. (Connect #2568)

GAE/src/META-INF/jdoconfig.xml, GAE/war/WEB-INF/web.xml
Flow would not build in Eclipse.
Updated jdoconfig.xml and web.xml
=> [#2696]Make Flow build in OOB Eclipse Luna. (Connect #2696)

GAE/src/org/waterforpeople/mapping/app/web/ImageCheckServlet.java, GAE/src/org/waterforpeople/mapping/dataexport/service/BulkDataServiceClient.java
Lint found two minor issues.
Fix them.
=> Issue/2700 lint fixes (Connect #2700)

GAE/src/com/gallatinsystems/framework/dao/BaseDAO.java, GAE/src/com/gallatinsystems/survey/dao/CascadeNodeDao.java, GAE/src/com/gallatinsystems/survey/dao/DataPointApprovalDAO.java, GAE/src/com/gallatinsystems/survey/dao/QuestionOptionDao.java, GAE/src/com/gallatinsystems/user/dao/UserAuthorizationDAO.java, GAE/src/org/waterforpeople/mapping/analytics/dao/SurveyQuestionSummaryDao.java, GAE/src/org/waterforpeople/mapping/dao/SurveyInstanceDAO.java
Unnecessary logging. Warnings about unchecked casts.
Remove logging. Suppress warnings.
=> Issue/2702 stop logging non spring auth (Connect #2702)

Dashboard/app/js/lib/models/models.js
There is no user field in this API anymore.
Remove it from the dashboard.
=> [#2713]Remove user field. (Connect #2713)

GAE/pom.xml, GAE/war/WEB-INF/dev-logging.properties
Fixed #2724
level should be FINE, not DEBUG
Setting also a better log format.
=> DEBUG level not working in dev env

GAE/war/WEB-INF/dev-logging.properties
=> Change package name to log (connect #2724)

GAE/pom.xml
=> Replace hard coded appengine version with variable (connect #2641)

Dashboard/app/dashboard.html
Integrity check for Carto libraries failing on CartoDB enabled instances causing maps not to work
Fix resource integrity
=> Fix Carto libraries integrity (connect #2721)

GAE/src/org/akvo/flow/rest/ReportRestService.java, GAE/src/org/akvo/flow/rest/dto/ReportTaskRequest.java, GAE/src/org/akvo/flow/servlet/ReportServlet.java, GAE/war/WEB-INF/webapp-security.xml
Not enough params to report engine
Add some
=> [#2719]Add parameters. (Connect #2719)

scripts/deploy/bootstrap-deploy.sh
=> Fix broken packages for deployment docker script (connect #2704)

GAE/src/org/akvo/flow/servlet/ReportServlet.java
Wrong data format when triggering report engine
Format it properly
=> [#2719]Fix data parameters. (Connect#2719)

Dashboard/app/js/lib/controllers/reports-controllers.js, Dashboard/app/js/lib/views/reports/export-reports-views.js, Dashboard/app/js/lib/views/views.js
* reports list not updating after generating new report
* checking if reports exist not working
* reports sorted by date ascending
* reports path prefixed by "Root"
* if there are reports still generating, check is state has changed every 5 seconds
* change how we check for reports availability and display "no reports" if none
* sort reports by date descending
* remove "Root" prefix from reports path
=> Downloadable exports (connect #2505)

GAE/src/org/akvo/flow/servlet/ReportServlet.java
=> [#2719]Handle null date parameters. (Connect #2719)

Dashboard/app/js/templates/navReports/reports-list.handlebars, GAE/src/locale/en.properties, GAE/src/locale/ui-strings.properties
Dates not displaying properly
Change how dates are displayed
=> Change submissions date text (connect #2505)

Dashboard/app/js/lib/controllers/reports-controllers.js, Dashboard/app/js/lib/views/reports/export-reports-views.js, Dashboard/app/js/templates/navReports/export-reports.handlebars, GAE/src/locale/en.properties, GAE/src/locale/ui-strings.properties
When user clicks download, they're auto-navigated back to reports list
Remove auto-navigation and add "back" button
=> Do not autonavigate back to reports list (connect #2505)

GAE/src/org/akvo/flow/rest/ReportRestService.java
Users could delete reports by other users
Check that it belongs to the deleter
=> [#2719]Plug security hole. (Connect #2719)

GAE/src/org/akvo/flow/servlet/ReportServlet.java
email should go in opts
move it
=> [#2719]Move email parameter. (Connect #2719)

GAE/src/org/akvo/flow/rest/ReportRestService.java, GAE/src/org/akvo/flow/servlet/ReportServlet.java
No email notifications
Transfer them in the right place
=> Fix email notification for release (Connect #2719)

ci/mvn-deploy.sh
* Copy a missing jar to where its needed
=> Copy missing jar (connect #2756)

Dashboard/app/js/lib/controllers/permissions.js, Dashboard/app/js/lib/views/reports/export-reports-views.js, Dashboard/app/js/templates/navReports/export-reports.handlebars, GAE/src/locale/en.properties, GAE/src/locale/ui-strings.properties
User has to click on "Back to reports" to get back to reports list
Navigate back to reports list after confirming report generation
=> Navigate to reports list after genrating report (connect #2505)

Dashboard/app/css/main.scss
Hard-coded height causing empty spaces on some tabs
Remove
=> [#2505] remove hard-coded height

Dashboard/app/css/main.scss, Dashboard/app/js/templates/navReports/export-reports.handlebars
Removed height restriction restoring a previous problem
Restore height restriction but limit it to reports tab
=> Restrict min-height to reports tab (connect #2505)

Dashboard/app/css/main.scss, Dashboard/app/js/lib/views/reports/export-reports-views.js
Dashboard footer sticky-ing at bottom of reports list tab and geoshape report generate button missing
Remove sticky-ing of footer and restore geoshape report type generate button
=> Scrollable exports list (connect #2505)

Dashboard/app/js/templates/navData/data-cleaning.handlebars
Wrong view set for data cleaning
Set correct view
=> Set correct view for data cleaning (connect #2505)

Dashboard/app/js/lib/models/models.js
questionId property not sent affecting geoshape reports
send questionId
=> Send questionId property when generating report (connect #2505)

GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
Did not handle null cells with other properly in all cases.
Check for that, too.
=> Issue/2660 import other singleselect (Connect #2660)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
When an OPTION question had no options, the export threw an NPE.
Handle it.
=> [#2777]Do not die if no options defined. (Connect #2777)

Dashboard/app/js/lib/views/surveys/question-view.js
Not possible to set barcode questions as data point name
Enable setting of barcode questions as data point name
=> Use barcode as data point name (connect #2776)

Config/instanceConfigurator/src/org/akvo/flow/templates/appengine-web.xml.ftl
=> Add java8 to the appengine-web.xml template file (connect #2395)

GAE/src/org/waterforpeople/mapping/app/web/ProcessorServlet.java
=> Ability to improve error messages when cascade publishing fails (connect #2794)

GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
When running the importer in the debugger, there would be no logging.
Add the simplest log config possible.
=> [#2780]Simplify debugging. (Connect #2780)

GAE/src/org/akvo/flow/rest/dto/ReportTaskRequest.java, GAE/src/org/akvo/flow/servlet/ReportServlet.java
Task would try to start report forever.
Stop after 5 tries.
=> [#2779]Stop trying to start a report after 5 tries. (Connect #2779)

Dashboard/app/dashboard.html
Sub-resource integrity checks failing for CartoDB libraries
Regenerate the sub-resource integrity hash
=> Hotfix for cartoDB libraries sub-resource integrity check failure (connect #2812)

Dashboard/app/js/lib/models/models.js
No checks for whether a surveyGroup is selected after the survey endpoint completes loading leading to errors
Add check for selected SurveyGroup
=> Add check for selected surveyGroup (connect #2821)

Dashboard/app/js/lib/views/reports/export-reports-views.js
Reports list not displaying if surveys endpoint is not ready or has failed
Check for ancestorIds before looping though
=> Fix failure to display of reports list when surveys endpoint fails/has not completed (connect #2823)

Dashboard/app/js/lib/views/reports/export-reports-views.js, Dashboard/app/js/lib/views/views.js, Dashboard/app/js/templates/navData/data-cleaning.handlebars
List dot appearing on data cleaning tab
Remove view wrapper causing dot to display
=> Remove dot appearing on data cleaning tab (connect #2826)

Dashboard/app/js/lib/views/reports/export-reports-views.js
After clicking to generate report, dashboard not auto-navigating back to reports list
Restore auto-navigating
=> Restore reports autonavigation back to reports list (connect #2833)

Dashboard/app/js/lib/models/models.js
Orphan forms resulting in parts of dashboard breaking
Filter out orphan forms
=> Filter out forms without ancestors (connect #2821)

Dashboard/app/js/lib/views/reports/export-reports-views.js
If a survey ancestor has no name when generating the path, an error is thrown
Check if ancestor has a name
=> Confirm ancestor has a name (connect #2821)

Dashboard/app/js/lib/models/models.js
Checking if form has ancestors
Specify at least one
=> Confirm has more than one ancestor (connect #2821)

Dashboard/app/js/lib/views/reports/export-reports-views.js
Unregistered uploader events causing file upload progress not to show
Register events
=> Register uploader events (connect #2855)

Dashboard/app/js/lib/views/surveys/survey-details-views.js
When copying a questions group, copying runs endlessly
Check for status and stop fetching once complete
=> Stop endless group copying when copying complete (connect #2802)

Dashboard/app/js/lib/views/views.js, Dashboard/app/js/templates/navData/question-answer.handlebars
Link to a submitted video displayed with an option to view it in a separate tab
Hide link and give user option to view video on the same page
=> Show videos in UI (connect #2561)

dev-deploy.sh
* Copy the missing jar for dev deployments
=> Copy missing jar for dev environment deployments (connect #2816)

Dashboard/app/js/lib/views/views.js
Geoshape response types not rendering on maps tab
Changed how we check for geoshape type questions
=> Render geoshape responses on maps (connect #2884)

Dashboard/app/css/main.scss
Unused sorting arrows in the tables under inspect data and monitoring tabs
Remove arrows using the unused `noArrows` class
=> Remove unnecesary sorting arrows in the inpect data and monitoring tabs (connect #2389)

Dashboard/app/js/lib/views/data/inspect-data-table-views.js, Dashboard/app/js/lib/views/views.js, Dashboard/app/js/templates/navData/inspect-data.handlebars, Dashboard/app/js/templates/navData/monitoring-data.handlebars
`surveyCode` property used to show path across the dashboard and not reflecting changes
Remove path from some parts of UI and make it a computed property when needed
=> Change how survey path is displayed (connect #2507)

Dashboard/app/js/lib/views/views.js
=> Log what's failing when rendering some caddisfly responses (connect #1750)

Dashboard/app/js/lib/views/views.js
Caddisfly JSON response parsed multiple times on maps
Reduce parsing
=> Change how we handle caddisfly response (connect #1750)

Dashboard/app/js/lib/views/views.js
=> Revert how we handle caddisfly response

Dashboard/app/js/lib/views/views.js
Caddisfly responses with escape characters failing to parse
Stringify response before parsing
=> Stringify caddisfly responses before parsing (connect #1750)

Dashboard/app/js/lib/views/views.js
Caddisfly response containing escape characters breaking parsing
Remove escape characters
=> Remove escape characters on response (connect #1750)

GAE/src/com/gallatinsystems/framework/dao/BaseDAO.java
On a local server, tasks failed to save entities.
Check for nulls.
=> [#2909]Protect against NPEs. (Connect #2909)

GAE/src/com/gallatinsystems/survey/dao/QuestionDao.java
=> [#2911]Improve fixup logic. Unbreak some lines. (Connect #2911)

GAE/src/org/waterforpeople/mapping/app/web/CronCommanderServlet.java
Too much server load for /devicenotification.
Cull entries form DFJQ faster.
=> [#2913]Forget about device files after one year.

Dashboard/app/js/templates/application/footer.handlebars
Link to terms of service needed to be updated
Update url
=> Update terms of service url (connect #2898)

Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/lib/views/surveys/question-view.js, Dashboard/app/js/templates/navSurveys/question-view.handlebars, GAE/src/locale/en.properties, GAE/src/locale/ui-strings.properties
Possible to save optionless option type questions
Disable this with an error message explaining to user
=> Disable saving optionless questions

Dashboard/app/js/lib/controllers/maps-controllers-common.js, Dashboard/app/js/lib/views/maps/map-views-common.js, Dashboard/app/js/templates/navMaps/nav-maps-common.handlebars
`No submissions...` message displayed to user before data has completed pulling
Change how submissions are managed
=> Manage how the form filter handles submissions(connect #2770)

Dashboard/app/js/templates/navSurveys/question-view.handlebars
Options validation affecting other question types
Restrict option validation only to option type questions
=> Fix validation affecting other question types (connect #2150)

Dashboard/app/js/lib/models/FLOWrest-adapter-v2-common.js, Dashboard/app/js/lib/views/reports/export-reports-views.js, GAE/src/locale/en.properties, GAE/src/locale/ui-strings.properties
survey/form filters not displaying for exporting reports
Handle cases where one/more of a survey's ancestors no longer exist causing the issue
=> survey/form filters not displaying for exporting reports (connect #2938)

Dashboard/app/js/lib/models/FLOWrest-adapter-v2-common.js
403 (forbidden) error responses not getting handled causing some parts of the dashboard to fail
Install generic error handling to at least clear loading animation and allow other features to continue working
=> Handle 403 error response (connect #2948)

GAE/src/com/gallatinsystems/device/dao/DeviceDAO.java, GAE/src/com/gallatinsystems/survey/dao/SurveyAssignmentDAO.java, GAE/src/org/waterforpeople/mapping/app/web/CronCommanderServlet.java, GAE/war/WEB-INF/cron.xml
=> Issue/2939 purge old devices (Connect #2939)

scripts/data/src/org/akvo/gae/remoteapi/PrintTreeStructure.java
=> Issue/2978 tree script mandatory flag (Connect #2978)

.gitignore, GAE/src/com/gallatinsystems/common/util/ZipUtil.java, GAE/src/org/waterforpeople/mapping/app/web/BootstrapGeneratorServlet.java
boostrap generation fails as xml files no longer generated on s3
fixed boostrap survey xml file not found
+ added tmp folder to list of ignored folders
NA
=> [#2980] bootstrap generation fix (connect #2980)

Dashboard/app/js/lib/views/surveys/question-view.js
Dependent question not assigned to variable causing reordering options to disappear
Assign variable
=> Assign dependentQuestion to a variable (connect #2891)

Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/lib/views/surveys/survey-group-views.js
The way we were looking for registration form in monitoring survey causing problems
Change how we look for registration form
=> Change how we look for registration form (connect #2917)

GAE/pom.xml
* Address the further security warnings from github
=> [#2896] Upgrade jackson library to address further security warnings

GAE/src/org/waterforpeople/mapping/app/web/ProcessorServlet.java, GAE/war/WEB-INF/cron.xml, GAE/war/WEB-INF/queue.xml
Two or more threads could ingest the same file at at the same time.
Run on a special queue that will not allow that.
=> Issue/2944 si sl duplication race (connect #2944)

GAE/pom.xml
=> Remove unused POM dependencies (connect #3002)

GAE/src/org/waterforpeople/mapping/app/web/DataProcessorRestServlet.java
* use frontend (instance) workers and split assembly into individual tasks per datapoint
=> Stop using backends for datapoint name assembly

GAE/src/org/waterforpeople/mapping/app/web/DataProcessorRestServlet.java, GAE/src/org/waterforpeople/mapping/app/web/TestHarnessServlet.java
* Remove backend header from task creation requests.
=> Remove backend request when creating dataprocessor tasks (connect #2972)

Dockerfile, GAE/war/WEB-INF/backends.xml, ci/mvn-deploy.sh, dev-deploy.sh
* We will no longer be using the backends so we remove the configuration and deployment code
=> Remove backends deployment configuration and deployment code (connect #2694)

scripts/deploy/bootstrap-deploy.sh
broken builds due to missing NSS
add nss also to bootstrap-deploy.sh
NA
=> Update bootstrap-deploy.sh (connect #3017)

scripts/deploy/deploy.sh
Mentioned backend to Google.
Stop that.
=> [#3026]Stop updating the backend. (Connect #3026)

GAE/src/org/waterforpeople/mapping/app/web/EnvServlet.java, RELEASE_NOTES.md
If a user is not found EnvServlet would throw an NPE.
Check for that.
=> Issue/3022 npe in envservlet (Connect #3022)

GAE/src/org/akvo/flow/events/EventLogger.java, GAE/src/org/akvo/flow/events/EventUtils.java, scripts/data/export_auth_data_to_event_log.sh, scripts/data/src/org/akvo/gae/remoteapi/ExportAuthDataToEventLog.java
See #3031 
After the release, we need to do an initial dump of the existing Auth data into the EventQueue.
=> Auth data to Unilog

Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/templates/navSurveys/question-view.handlebars, GAE/src/locale/en.properties, GAE/src/locale/ui-strings.properties
No limit on number of characters an option can have
Add limit
=> Do not allow saving option suestion if an option has over 500 characters

GAE/src/org/waterforpeople/mapping/app/web/DataProcessorRestServlet.java
=> [#3043]Remove backend.

Dockerfile
=> #1502 added npm install to dockerfile

Dockerfile
npm packages not installing because of missing package.json file
fix issue
=> Fix npm issue

ci/build.sh
Files from vendor dir are responding with 404. I removed the ruby part of the build and I think this was a mistake.
Added the ruby component of the build back.
=> #1502 added back rake build command

Dashboard/app/js/lib/mixins/observe.js, Dashboard/app/js/lib/views/devices/assignments-list-view.jsx, Dashboard/package-lock.json, Dashboard/package.json, Dashboard/webpack.config.dev.js
Needed to see if the bundle size produced by webpack could be optimized in terms of file size.
Swapped out 3rd party deps for more lightweight alternatives; made imports more granular.
=> optimize webpack build/bundle size #3036

.travis.yml
Travis is not logging builds to slack.
Added notification config to travis.yml.
=> travis slack notifications #3052

Dashboard/app/css/users.scss, Dashboard/app/js/lib/main.js
users page was looking unstyled
included the import for the users.scss file
=> #1502 added users css file

Dashboard/package-lock.json, Dashboard/package.json, Dashboard/scripts/buildDev.js, Dashboard/scripts/buildProd.js, Dashboard/scripts/buildUsersCss.js
needed to compile a separate css file for the users page - not just add the css to the bundle.
a script to compile the css file in the target dir
=> #1502 added script for compiling users page css

Dashboard/app/js/lib/main.js, Dashboard/app/js/templates/navDevices/assignment-list-tab/assignment-list.handlebars
Top parts of devices and assignments list hidden
Remove require of library that was causing this
=> Assignment list layout

ci/devserver.sh
=> #3035 devserver script removed typo

ci/build.sh
=> #3035 remove ruby build fix

ci/devserver.sh
Tail command in devserver breaking build
Fix command
=> Fix broken tail command

Dashboard/package.json
=> #3035 made post merge git script silent

GAE/src/com/gallatinsystems/survey/dao/CaddisflyResourceDao.java, GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Reports were using the old caddisfly test definitions file.
Use the new one. Required handling tests with no hasImage item.
=> [#3077]Use new test definitions file. Handle nulls for hasImage.

Dashboard/app/js/lib/router/router.js, Dashboard/app/js/lib/views/views.js
Code referencing deleted files
Removed it
=> Remove code referencing deleted files

Dashboard/app/js/lib/views/reports/export-reports-views.js, Dashboard/app/js/templates/navReports/export-reports.handlebars
=> [#3073] Cleanup unused applet code

Dashboard/app/js/lib/controllers/permissions.js, Dashboard/app/js/lib/views/views.js, Dashboard/app/js/templates/application/navigation.handlebars
=> Devices tab not showing (connect #3083)

Dashboard/app/js/lib/controllers/device-controllers.js, Dashboard/app/js/templates/navDevices/devices-list-tab/devices-list.handlebars
Ability to select all devices
Remove ability
=> Remove ability to select all devices (connect #3051)

Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/lib/views/devices/assignment-edit-views.js
The way we loop through objects affecting functionality due to performance check
Change how we loop through objects
=> Looping through objects (connect #3088)

GAE/src/com/gallatinsystems/survey/domain/xml/Question.java, GAE/src/org/waterforpeople/mapping/app/web/SurveyAssemblyServlet.java
variableName was not published, making it impossible to perform an export relying only on the xml file.
Add it.
=> [#3101]Add variableName to published question properties.

Dashboard/package-lock.json, Dashboard/package.json, GAE/pom.xml
* We had security warnings and missing peer package warnings
* Upgrade relevant npm packages
* Upgrade maven packages for spring and spring-security
=> [#3098] Upgrade library versions

scripts/data/src/org/akvo/gae/remoteapi/DeleteData.java, scripts/data/src/org/akvo/gae/remoteapi/DeleteFormCompletely.java, scripts/data/src/org/akvo/gae/remoteapi/DeleteSurveyIfEmpty.java
Also make DeleteData script survive missing form entity.
Need to remove many forms and their data.
Make a new script for deleteing forms. DeleteData script will be run first.
=> [#3075]New scripts to delete all aspects of a form. 

GAE/pom.xml
* Upgrade library to address security alert
=> [#3098] Upgrade the jackson libraries

GAE/src/org/waterforpeople/mapping/app/web/SurveyAssemblyServlet.java
* Remove a misleading message when surveys are published
=> [#3123] Replace the extension of the uploaded published survey file

GAE/src/com/gallatinsystems/surveyal/domain/SurveyedLocale.java
Some data point identifiers were too short: xxxx-xxxx-xxx
Ensure there are always 12 alphanumerical characters.
=> [#3117]Reinstate suppressed leading zeroes.

Dashboard/app/js/lib/components/ChildOption.jsx, Dashboard/app/js/lib/views/folder-survey-selector.jsx, Dashboard/app/js/lib/views/views.js, Dashboard/app/js/templates/navDevices/assignment-edit-tab/assignment-edit.handlebars
Folder/survey selector implemented in ember
Re-implement logic in react
=> Folder survey selector in react

Dashboard/app/js/lib/views/folder-survey-selector.jsx
Folder/survey selector in react not sorted
Sort
=> Sort folder/survey selector by name (connect #3109)

GAE/src/org/waterforpeople/mapping/app/web/rest/ResourceNotFoundException.java, GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyAssignmentRestService.java
* The assignments entities code attempted to update assignments by identifying which entities needed to be newly generated, which ones deleted and which ones possibly updated.
* Simplify the entities generation by always deleting all entitites associated with an assignment an regenerating the new ones
=> [#3108] Refactor assignments entities generation

scripts/data/src/org/akvo/gae/remoteapi/SplitAssignments.java
The #n part of the name was redundant.
Remove it.
=> [#3153]Simplify name.

scripts/data/export_auth_data_to_event_log.sh, scripts/data/src/org/akvo/gae/remoteapi/ExportAuthDataToEventLog.java
Adding SurveyGroups to Unilog after the clean up. 
Script already run in test and production.
Part of #3031
=> Exporting SurveryGroups

Dashboard/app/js/lib/components/Checkbox.jsx, Dashboard/app/js/lib/views/devices/assignment-edit-views.js, Dashboard/app/js/lib/views/forms-selector.jsx, Dashboard/app/js/lib/views/views.js, Dashboard/app/js/templates/navDevices/assignment-edit-tab/assignment-edit.handlebars, GAE/src/locale/en.properties, GAE/src/locale/ui-strings.properties
Form selection via select list and able to select multiple forms from different surveys
Change selection to checkboxes as per design and restrict selection to forms from one survey per assignment
=> Assignments form selection (connect #3136)

.gitignore, Dashboard/.eslintrc, Dashboard/app/js/lib/components/Checkbox.jsx, Dashboard/app/js/lib/components/selectors/DeviceSelector.jsx, Dashboard/app/js/lib/views/selectors/device-selector.jsx
Moved all DOM functionality to DeviceSelector react class
=> Convert device selector to class

GAE/war/auth0/error.html
=> Adapt email verification error page to current Lumen

GAE/war/register.html
=> Adapt register.html to i18n and to share lumen design

Dashboard/app/public.ejs
Once a user types his instance name he will land on the login page
=> [#2559] Added redirect  to login page

Dashboard/app/js/lib/components/selectors/FolderSurveySelector/FolderSurveySelector.test.jsx, Dashboard/app/js/lib/components/selectors/FolderSurveySelector/__snapshots__/FolderSurveySelector.test.jsx.snap
=> [#3212] - fix folder selector tests

Dashboard/app/css/main.scss
=> [#3224] - remove ui middle line

GAE/src/org/akvo/flow/rest/security/RedirectIndexFilter.java, GAE/war/WEB-INF/webapp-security.xml
* A redirect was added to the HTML in the page but the public maps still showed for a few seconds before the redirect was activated.
* Add a filter that redirects even before loading the public HTML pages
=> [#2559] Add a new redirect filter

scripts/data/src/org/akvo/gae/remoteapi/SplitAssignments.java
NPE if form id was null
Check for that
=> [#3240]Handle null form ID.

GAE/pom.xml
* CVE-2019-14540
* CVE-2019-16335
=> [#3098] Update Jackson

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
An RQG on a published form caused an NPE in report generator.
Use correct key for map lookup.
=> Issue/3249 Handle RQGs (connect #3249)

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Boolean options from Clojure resulted in
"java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String"
Use toString() on potentially-boolean options. Somewhat experimental.
=> [#3252]Always compare strings.

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Still breaks.
Try another approach to the bogus type of boolean options.
=> [#3252]Go via Object to avoid all compiler assumptions.

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Trivial copy-paste mistake.
Fix it.
=> [#3252]Fix copy-paste error.

Dashboard/app/js/lib/components/selectors/DeviceSelector/DeviceAccordion.jsx, Dashboard/app/js/lib/components/selectors/DeviceSelector/DeviceSelector.test.jsx, Dashboard/app/js/lib/components/selectors/DeviceSelector/__snapshots__/DeviceSelector.test.jsx.snap, Dashboard/app/js/lib/components/selectors/DeviceSelector/index.jsx, Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
=> [#3234] - move select all checkbox to accordion

GAE/war/WEB-INF/web.xml
=> Allow only cookies for session tracking

Dashboard/app/js/lib/components/devices/AssignmentsEditView/index.jsx, Dashboard/app/js/lib/components/devices/AssignmentsEditView/styles.scss
Suggestions here: 
1: [*from Mulo*](https://github.com/akvo/akvo-flow/issues/3226#issuecomment-549398826) 
2: [*from Jana*](https://github.com/akvo/akvo-flow/issues/3226#issuecomment-549706895)
=> [#3226] - update assignments ui with new suggesstion

Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
=> [#3270] - filter out unpublished forms in assignments ui

GAE/src/org/waterforpeople/mapping/serialization/response/MediaResponse.java, scripts/data/src/org/akvo/gae/remoteapi/ExtractImageGeotag.java
Geotags in image Exif were not extracted by the app for a while, and thus do not show up in the UI.
Retroactively extract them via a datascript.
=> [#3180]Extract-missing-geotags script.

Dashboard/__mocks__/fileMock.js, Dashboard/__mocks__/styleMock.js, Dashboard/app/js/lib/components/reusable/Checkbox/index.jsx, Dashboard/app/js/lib/components/selectors/DeviceSelector/__snapshots__/DeviceSelector.test.jsx.snap, Dashboard/app/js/lib/components/selectors/DeviceSelector/index.jsx, Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx, Dashboard/jest.config.json
=> [#3281] - fix checkbox

Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
Forgot to set the devices in the selected assignment. Fixed now
=> [#3284] - set deviceIds in selected assignments

Dashboard/app/js/lib/components/devices/AssignmentsEditView/index.jsx, Dashboard/app/js/lib/components/devices/AssignmentsEditView/styles.scss, Dashboard/app/js/lib/components/reusable/SwitchBox/index.jsx, Dashboard/app/js/lib/components/reusable/SwitchBox/style.scss, Dashboard/app/js/lib/components/selectors/FormSelector/index.jsx, Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
=> [#3290] - assignments forms ui fixes

Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
=> [#3302] Refactor variables and properties to clarify their usage

Dashboard/app/js/lib/views/stats/stats-lists.jsx
=> Issue 3299/stats list not loading

scripts/data/src/org/akvo/gae/remoteapi/UnAssignUnPublishedForms.java, scripts/data/unassign_unpublished_forms.sh
if unpublished forms have been assigned, remove them
=> [#3298] script to fix SurveyAssigment and DeviceSurveyJobQueue

GAE/src/org/akvo/flow/xml/XmlForm.java, GAE/src/org/waterforpeople/mapping/app/web/SurveyAssemblyServlet.java, GAE/test/org/akvo/flow/xml/FlowXmlObjectWriterTests.java
* Reorder the attributes to match the previous XML generation format
=> [#3316] Refactor XMLForm survey attributes order

GAE/src/org/akvo/flow/xml/XmlQuestionGroup.java, GAE/test/org/akvo/flow/xml/FlowXmlObjectWriterTests.java
repeatable should be either true missing from form xml
=> [#3316] fix repeatable group should not be set when false

GAE/src/org/akvo/flow/xml/XmlOption.java, GAE/src/org/akvo/flow/xml/XmlOptions.java, GAE/test/org/akvo/flow/xml/FlowXmlObjectWriterTests.java
* avoid NPE translation map
* add tests
* return default renderType
* reorder fields as were before
=> [#3316] Fixes for question options

GAE/src/org/akvo/flow/xml/XmlForm.java, GAE/src/org/waterforpeople/mapping/app/web/SurveyAssemblyServlet.java, GAE/test/org/akvo/flow/xml/FlowXmlObjectWriterTests.java
App attribute was not given a value when publishing
Give it one. Update tests.
=> [#3316]Use the 'app' atribute.

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java, GAE/src/org/waterforpeople/mapping/dataexport/SurveyFormExporter.java
Empty group triggered an NPE and woud otherwise have been invisible in form details export.
Guard against NPE, show empty groups.
=> Issue/3334 form export must handle empty QG (Connect #3334)

Dashboard/package-lock.json, GAE/src/com/gallatinsystems/framework/dao/BaseDAO.java, GAE/src/com/gallatinsystems/surveyal/dao/SurveyedLocaleDao.java, GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyedLocaleRestService.java
There was no way to search for data points with a prefix of the displayName matching a string. 
Add one.
=> Issue/3343 search dps by displayname prefix (Connect #3343)

scripts/data/delete-kind.sh
* See https://cloud.google.com/datastore/docs/bulk-delete
* Dependencies:
- gcloud: https://cloud.google.com/sdk/
- jq: https://stedolan.github.io/jq/
=> [#3349] Use Dataflow for deleting all entities of a Kind

GAE/src/services/TranslationGenerator.java
Adds support for translation generation to `.jsx` files
=> [#3352] Add translation support for .jsx files

scripts/data/delete-kind.sh
Instead of `gcloud config set core/project` to define the project
we want, use `--project` in all calls to APIs.
This has the benefit of running the same script in parallel with
multiple projects at the same time.
=> [#3349] Use project as parameter to be able to execute in parallel

Dashboard/app/js/lib/components/reusable/Checkbox/Checkbox.test.jsx, Dashboard/app/js/lib/components/reusable/Checkbox/__snapshots__/Checkbox.test.jsx.snap, Dashboard/app/js/lib/components/reusable/SwitchBox/SwitchBox.test.jsx, Dashboard/app/js/lib/components/reusable/SwitchBox/__snapshots__/SwitchBox.test.jsx.snap, Dashboard/app/js/lib/components/reusable/SwitchBox/index.jsx, Dashboard/app/js/lib/components/selectors/DeviceSelector/DeviceAccordion.jsx, Dashboard/app/js/lib/components/selectors/DeviceSelector/DeviceSelector.test.jsx, Dashboard/app/js/lib/components/selectors/DeviceSelector/__snapshots__/DeviceSelector.test.jsx.snap, Dashboard/app/js/lib/components/selectors/FolderSurveySelector/FolderSurveySelector.test.jsx, Dashboard/app/js/lib/components/selectors/FormSelector/FormSelector.test.jsx, Dashboard/app/js/lib/components/selectors/FormSelector/__snapshots__/FormSelector.test.jsx.snap, Dashboard/app/js/lib/components/stats/__tests__/NewStats.test.jsx, Dashboard/app/js/lib/components/stats/__tests__/StatsLists.test.jsx, Dashboard/app/js/tests/setupTests.js, Dashboard/jest.config.json
Add test suites for components used in the assignments edit page
=> Issue 3341/tests for assignments ui

GAE/src/org/akvo/flow/xml/XmlQuestionGroup.java, GAE/test/org/akvo/flow/xml/FlowXmlObjectWriterTests.java
when a group is non repeatable 
fix when non repeatable group we should not pass repeatable=false
NA
=> [#3316] fix for non repeatable groups survey xml files

GAE/war/WEB-INF/datastore-indexes.xml
An index was missing in the datastore.
Define it in datastore-indexes.xml
=> [#3368]Add index. Reformat QAS entries w spaces.

GAE/src/org/waterforpeople/mapping/dataexport/SurveyFormExporter.java
Min and max columns on form export had the headers exchanged.
Swap them.
=> [#3340]Switch order of min-max headers.

GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyedLocaleRestService.java
Could fetch all datapoints, (variously filtered,) but not by a list of ids.
Add the `ids` parameter, and handle it.
=> [#3387]Handle GET for a list of datapoint ids.

GAE/src/org/akvo/flow/events/EventUtils.java
Added `status` property when logging events for `Form` entity
=> [#3401] Add status property when logging events for Forms

GAE/src/org/waterforpeople/mapping/dataexport/StatisticsExporter.java
Files are named .xlsx, but are in xls format. Long unsorted lists are hard to interpret.
Use xlsx-generating POI classes. Sort the surveys by path.
=> [#3399]Make xlsx files. Sort the surveys by path.

Dashboard/app/js/lib/components/devices/AssignmentsEditView/index.jsx, Dashboard/app/js/lib/components/devices/AssignmentsEditView/screens/FormSection.jsx, Dashboard/app/js/lib/components/reusable/DatePicker/index.jsx, Dashboard/app/js/lib/components/reusable/DatePicker/style.scss, Dashboard/package-lock.json, Dashboard/package.json
Date picker across browsers was inconsistent.
Using a unified  date picker that works across browsers
=> [#3223] - use js datepicker

GAE/src/org/akvo/flow/rest/DataPointAssignmentRestService.java
=> [#3425] Clear error message in the OK path

Dashboard/app/js/lib/components/devices/AssignmentsEditView/screens/AssignDatapoints/SearchDatapoints.jsx, Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
It's possible to assign data points that does not belong to the survey
Clear previously searched datapoints
=> [#3431] - clear datapoints list after search

Dashboard/package-lock.json, Dashboard/package.json, Dashboard/webpack.config.prod.js
Lots of redundant comments were in the dashboard bundle file
Use the `uglify` plugin to remove these redundant comments
=> [#3416] - use uglify plugin to remove comments from prod bundle

Dashboard/app/js/lib/components/devices/AssignmentsEditView/screens/AssignDatapoints/SearchDatapoints.jsx
=> [#3437] - remove ghost search icon when searching for datapoints

Dashboard/app/js/lib/components/devices/AssignmentsEditView/screens/AddDevices.jsx, Dashboard/app/js/lib/components/devices/AssignmentsEditView/screens/EditDevices.jsx, Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
Device and device groups are not sorted making it hard to find a device or device group
Sort devices and the device group using lodash and array sort functionality
=> [#3447] - sort device and device groups for assignments

GAE/src/com/gallatinsystems/framework/rest/RestRequest.java, GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
Import of data from reports is run as a request to a frontend GAE instance
We add an extra parameter to convert the request to a task
=> [#3433] Run import of form instances as a task

Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
Date validation always fails
Remove length check in date validation
=> [#3462] - remove null check for date validation

GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java
* New instances were created instead of updating existing ones
* Fix the url parameter separator
=> [#3433] Add parameter separator in URL

GAE/pom.xml, GAE/src/com/gallatinsystems/framework/rest/AbstractRestApiServlet.java, GAE/src/com/gallatinsystems/framework/rest/RestRequest.java, GAE/src/com/gallatinsystems/framework/servlet/ExecuteRequestAsTaskFilter.java, GAE/test/com/gallatinsystems/framework/servlet/ExecuteRequestAsTaskFilterTests.java, GAE/war/WEB-INF/web.xml
* Request to task conversion handled in a servlet
* We intercept the request in a filter so that we don't process / parse it unnecessarily since it will go to a task.
=> [#3451] Implement request to task filter

Dashboard/app/js/lib/components/devices/AssignmentsEditView/screens/EditDevices.jsx
Change the sorting functionality in edit device page
=> [#3481] - change sorting method in edit device page

Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
Lots of unused code in the assignment file
Take the codes away and group related functionality together
=> [#3508] - remove unused code and organise assignments code

Dashboard/app/js/lib/components/devices/AssignmentsEditView/MainBody.jsx, Dashboard/app/js/lib/components/devices/AssignmentsEditView/__partials/SidebarDropdown.jsx, Dashboard/app/js/lib/components/devices/AssignmentsEditView/styles.scss
When in devices/datapoints page
When in forms page:
=> [#3503] - clean up assignment sidebar to look like mock-up

GAE/src/org/akvo/flow/domain/DataUtils.java, GAE/src/org/waterforpeople/mapping/app/web/rest/DeviceRestService.java, GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java, GAE/src/org/waterforpeople/mapping/dataexport/StatisticsExporter.java
Background info: https://stackoverflow.com/questions/513832/how-do-i-compare-strings-in-java/513839#513839
=> [#555] Use `equals()` instead of `==` for String comparison

scripts/data/src/org/akvo/gae/remoteapi/UnifyDataPointAssignment.java, scripts/data/unify.sh
=> [#3511] Add UnifyDataPointAssignment

Dashboard/app/css/main.scss, Dashboard/app/js/lib/components/devices/AssignmentsEditView/screens/AssignDatapoints/SearchDatapoints.jsx
- The [x] shows now a pointer icon so looks _clickable_
=> [#3521] After clicking 'Assign' we close the popup

Config/instanceConfigurator/build.xml
No way to clean old builds
Add clean step to ant file to remove old jars
NA
=> [#3541] adds clean step to config build.xml file + format file

Config/instanceConfigurator/src/org/akvo/flow/InstanceConfigurator.java
=> Add Sentry DNS opt

scripts/Readme.md, scripts/Readme.org, scripts/data/build.xml
=> [#3536] Improve ANT support for calling RemoteAPIServices

Dashboard/app/js/lib/analytics.js, Dashboard/app/js/lib/main.js, Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx
**what needed to be done?**
Add trackers to assignment file to track creating/updating assignments, and datapoints usage
[No Ui related changes]
=> Issue 3509/track assignment usage

Dashboard/app/js/lib/analytics.js
Bug with a typo in analytics file
Remove typo
Use new analytics url and correct site id
=> Issue 3509/fix typo bug in analytics file

ci/devserver.sh
When npm fails, the start up script will fail and the container will be stopped.
We also show a proper error message so that the developer is aware that something failed and where to look for the logs.
See #3569
=> Stop the akvo-flow container in dev env when npm fails

Dashboard/app/js/lib/components/forms/form-share/index.jsx, Dashboard/app/js/lib/components/forms/form-share/style.scss, Dashboard/app/js/lib/components/reusable/Modal/index.jsx, Dashboard/app/js/lib/components/reusable/Modal/style.scss, Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/lib/views/surveys/form-share.jsx, Dashboard/app/js/lib/views/views.js, Dashboard/app/js/templates/navSurveys/form.handlebars, Dashboard/package-lock.json, Dashboard/package.json
Add a share button to share web forms in survey page
=> Issue 3561/add option to share webform

Dashboard/app/js/lib/components/forms/form-share/index.jsx, Dashboard/app/js/lib/views/surveys/form-share.jsx
- Change the webform password
- Make registration forms shareable
- Close the modal when the user clicks on the "Done" button
=> [#3561] - make registration forms shareable

GAE/src/com/gallatinsystems/survey/domain/WebForm.java
validForm condition to check that form is not a monitoring form wasn't correct
=> [#3562] Fix validForm condition

Dashboard/app/js/lib/views/surveys/form-share.jsx
Relates #3575 
Adapt js logic to new form state
=> [#3575] Adapt logic to new form with no questions

Dashboard/app/js/lib/components/forms/form-share/index.jsx
=> [#3579] - add usage tracking to webforms

GAE/src/org/akvo/flow/api/app/WebFormRequest.java, GAE/src/org/akvo/flow/api/app/WebFormServlet.java, GAE/src/org/waterforpeople/mapping/app/web/EnvServlet.java, GAE/war/WEB-INF/web.xml, GAE/war/WEB-INF/webapp-security.xml
=> [#3145] Webform redirection

GAE/src/org/akvo/flow/api/app/WebFormServlet.java
=> [#3145] Fix retrieving flow name instance

GAE/src/com/gallatinsystems/survey/domain/WebForm.java
=> [#3145] Don't allow BARCODE (SCAN) question types

Dashboard/app/js/lib/models/models.js, Dashboard/app/js/lib/views/surveys/question-view.js, Dashboard/app/js/templates/navSurveys/question-view.handlebars
=> [#3576] - change key sent to the api

GAE/src/com/gallatinsystems/survey/domain/WebForm.java
=> Revert "[#3145] Don't allow BARCODE (SCAN) question types"

GAE/src/com/gallatinsystems/survey/domain/Question.java, GAE/src/org/akvo/flow/domain/mapper/QuestionDtoMappableFields.java, GAE/src/org/akvo/flow/xml/XmlQuestion.java, GAE/src/org/waterforpeople/mapping/app/gwt/client/survey/QuestionDto.java, GAE/test/org/akvo/flow/util/FlowJsonObjectWriterTests.java, GAE/test/org/akvo/flow/xml/FlowXmlObjectWriterTests.java
=> [#3576] Add Question.personalData boolean attribute [backend]

scripts/data/delete-repeat-iterations.sh, scripts/data/src/org/akvo/gae/remoteapi/DeleteRepeatQuestionGroupIteration.java
* Delete one or more iterations by specifying at the command line
* Update the iteration index in the responses if needed (not strictly necessary)
* Update the dependency libraries
=> [#3591] Datascript to delete specified iterations for a survey instance

Dashboard/app/js/lib/views/surveys/form-share.jsx, GAE/src/com/gallatinsystems/survey/domain/WebForm.java
=> [#3145] Allow Repeated Question Groups question types

GAE/src/com/gallatinsystems/survey/domain/Survey.java
* Check for null `webForm` field
=> [#3599] Fix NPE while publishing forms

GAE/pom.xml
* Spring security updated due to security issue #3604
=> Bump spring version to match updated spring security version

GAE/src/org/waterforpeople/mapping/app/web/SurveyAssemblyServlet.java
* Fix the NPE that happens during form publishing
=> [#3609] Fix the NPE for webforms validation when publishing surveys

GAE/src/com/gallatinsystems/survey/dao/CaddisflyResourceDao.java
Testing caddisfly new tests on uat2
=> Temporary use caddisfly dev file to test newly added test

GAE/src/com/gallatinsystems/survey/dao/CaddisflyResourceDao.java
=> Revert "Temporary use caddisfly dev file to test newly added test"

Dashboard/app/js/lib/views/surveys/question-view.js, Dashboard/app/js/templates/navSurveys/question-view.handlebars
Using Jquery, scroll to the position of the currently edited question when the save button is clicked.
=> [#3620] - scroll to the current edited survey question

Dashboard/app/js/lib/views/surveys/question-view.js
=> [#3620] - scroll to selected question on cancel

GAE/src/org/akvo/flow/events/EventUtils.java
=> Push Form and Form Instance versions to Unilog

GAE/src/com/gallatinsystems/survey/dao/SurveyDAO.java
* We make it possible to retrieve the survey definition but leave out the question options
=> [#3634] Refactor survey retrieval

Config/instanceConfigurator/src/org/akvo/flow/InstanceConfigurator.java
Details at:
https://github.com/akvo/akvo-flow/issues/3630#issue-687752606
=> [#3620] Sentry option named sentryDNS (Data Source Name)

scripts/data/src/org/akvo/gae/remoteapi/ExportDataToPG.java
* Failed to build remote API scripts
* Fix dependencies
=> [#3636] Fix dependency in remote script

Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/lib/models/models.js, GAE/src/com/gallatinsystems/survey/domain/Survey.java, GAE/src/org/waterforpeople/mapping/app/gwt/client/survey/SurveyDto.java, GAE/src/org/waterforpeople/mapping/app/util/DtoMarshaller.java, GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyRestService.java, GAE/src/org/waterforpeople/mapping/dataexport/service/BulkDataServiceClient.java
* Remove unused field in the survey domain object
=> [#3641] Remove unused field in the Survey domain object

GAE/src/com/gallatinsystems/common/util/S3Util.java, GAE/src/org/akvo/flow/api/export/DataBackoutServlet.java, GAE/src/org/waterforpeople/mapping/dataexport/service/BulkDataServiceClient.java, GAE/test/org/akvo/flow/util/Base64Test.java
=> [#3646] Use java.util.Base64 instead of org.apache.commons.codec

GAE/src/org/akvo/flow/api/app/DataPointUtil.java, GAE/src/org/waterforpeople/mapping/dao/SurveyInstanceDAO.java, GAE/test/com/gallatinsystems/surveyal/dao/SurveyInstanceDAOTest.java
NA
Fixed NPE when missing registration form submission for a given datapoint
NA
=> [#3652] attempt to fix NPE

GAE/src/org/waterforpeople/mapping/dao/SurveyInstanceDAO.java
=> [#3652] adds warning when datapoint without a form submission found

GAE/src/org/waterforpeople/mapping/dao/SurveyInstanceDAO.java
=> [#3645] Retrieve registration form instances in a single batch

GAE/src/org/akvo/flow/api/app/DataPointServlet.java
Found an issue in the implementation as the offset needs to be updated
=> [#3652] make sure to add an offset to the cursor

.semaphore/semaphore.yml
* https://docs.semaphoreci.com/ci-cd-environment/docker-authentication/
* https://docs.semaphoreci.com/ci-cd-environment/docker-authentication/#how-to-authenticate-docker-pulls
Closes #3662
=> [#3662] Use Docker Hub credentials for authenticated pulls

Dashboard/app/dashboard.ejs, Dashboard/app/js/lib/views/maps/map-views-common.js
=> [#3664] Update Mapbox from Classic (deprecated) to 'Mapbox styles'

scripts/data/fix-old-translations.sh, scripts/data/src/org/akvo/gae/remoteapi/FixOldTranslations.java
Some translations are missing surveyId and surveyGroupId and with the new logic #3669  they would not be copied
Create a script to fix the data
NA
=> [#3669] add a script to fix the translations ids

GAE/src/com/gallatinsystems/survey/dao/SurveyUtils.java, GAE/test/com/gallatinsystems/surveyal/dao/SurveyUtilsTest.java
=> [#3669] Refactor QuestionGroup copying to save in batches

GAE/src/com/gallatinsystems/survey/dao/SurveyUtils.java, GAE/src/org/waterforpeople/mapping/app/web/rest/QuestionRestService.java, GAE/test/com/gallatinsystems/surveyal/dao/SurveyUtilsTest.java, GAE/test/org/akvo/flow/api/app/DataStoreTestUtil.java
=> [#3669] Save copied questions and question options in batches

GAE/src/com/gallatinsystems/survey/dao/SurveyUtils.java, GAE/src/org/waterforpeople/mapping/app/web/DataProcessorRestServlet.java, GAE/src/org/waterforpeople/mapping/app/web/rest/ActionRestService.java, GAE/src/org/waterforpeople/mapping/app/web/rest/QuestionRestService.java, GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyRestService.java, GAE/test/com/gallatinsystems/surveyal/dao/SurveyUtilsTest.java, GAE/test/org/akvo/flow/api/app/DataStoreTestUtil.java
Co-authored-by: Marvin Kome <marvin@akvo.org>
=> [#3675] Reverted immutable flag and updated tests

GAE/src/com/gallatinsystems/survey/dao/SurveyUtils.java
=> [#3669] Remove unused method

scripts/data/remove_user.sh, scripts/data/remove_user_all_instances.sh, scripts/data/src/org/akvo/gae/remoteapi/RemoveUsers.java
=> [#3683] add script to remove users

GAE/src/com/gallatinsystems/survey/dao/SurveyUtils.java
=> [#3689] Remove debug logs

Dashboard/app/css/main.scss, Dashboard/app/js/templates/navSurveys/manage-translations.handlebars
=> [#3677] Set maxlength property for tooltip translations

GAE/src/com/gallatinsystems/survey/dao/QuestionGroupDao.java, GAE/src/org/akvo/flow/xml/XmlQuestionGroup.java, GAE/src/org/waterforpeople/mapping/app/gwt/client/survey/QuestionGroupDto.java, GAE/test/org/akvo/flow/util/FlowJsonObjectWriterTests.java
=> [#3685] added translations to question group

Dashboard/app/js/lib/controllers/controllers.js
Some homeless code that I came across while looking at something else.
=> [#3707] Remove ununsed roles code from UI

ci/check-property-encoding.sh
This PR does not enable anything in CI. It's only the start on a script to check encodings.
=> [#3711] Check properties file encoding script

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
After upgrading the libraries and then while testing it turned out when there was only one question in a group, the code crashed when trying to merge a cell
Only do the merge when at least 2 questions
NA
=> [#3716] fix error when group contains only one question

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java, GAE/src/org/waterforpeople/mapping/dataexport/service/BulkDataServiceClient.java
=> [#3727] Fixed issue with responses encoding

Dashboard/app/css/main.scss, Dashboard/app/js/lib/views/surveys/question-view.js, Dashboard/app/js/templates/navSurveys/question-view.handlebars, GAE/src/locale/ui-strings.properties
=> [#3715] Minor fixes

Dashboard/app/js/lib/controllers/languages.js
=> [#3733] added Sidaama language to dashboard

Dashboard/app/js/templates/navSurveys/question-view.handlebars
=> [#3738] Format: question-view.handlebars

GAE/src/com/gallatinsystems/survey/dao/SurveyDAO.java, GAE/test/com/gallatinsystems/survey/dao/SurveyDAOTest.java
Crash found (issue with publishing forms reported by partner)
fix the NPE (when group is not part of this form)
add test
NA
=> [#3740] Fix wrong group found crash + test

Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/lib/views/surveys/question-view.js, Dashboard/app/js/lib/views/surveys/survey-details-views.js, Dashboard/app/js/templates/navSurveys/edit-questions.handlebars
=> [#3715] More checks

GAE/src/com/gallatinsystems/survey/dao/SurveyUtils.java, GAE/test/com/gallatinsystems/surveyal/dao/SurveyUtilsTest.java
Some translations are not copied correctly
Make sure to update all translations
Added test to reproduce the issue
NA
=> [#3743] fixed issue with missing translations

GAE/src/org/waterforpeople/mapping/dataexport/SurveyReplicationImporter.java
=> [#3747] enabled logs

GAE/src/com/gallatinsystems/survey/dao/QuestionGroupDao.java, GAE/src/com/gallatinsystems/survey/dao/SurveyDAO.java, GAE/src/org/waterforpeople/mapping/dataexport/SurveyReplicationImporter.java
=> [#3747] make sure form and question group translations are copied

Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/lib/views/surveys/survey-group-views.js
Track only templates, not copying
=> [#3718] moves tracking to the right place

Dashboard/config/translations.yml
=> Remove old (not in use) translations

GAE/src/com/gallatinsystems/surveyal/app/web/SurveyalRestRequest.java, GAE/src/com/gallatinsystems/surveyal/app/web/SurveyalRestServlet.java, GAE/src/org/waterforpeople/mapping/app/web/dto/DataProcessorRequest.java, GAE/src/org/waterforpeople/mapping/app/web/rest/ActionRestService.java
* Cleanup the remaining ununsed code related to datapoint clustering
=> [#3755] Cleanup unused code related to datapoint clusters

GAE/src/org/akvo/flow/rest/handler/FormInstanceRequestHandler.java, GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyInstanceRestService.java, GAE/test/org/akvo/flow/rest/handler/FormInstanceRequestHandlerTests.java
=> [#3755] Add test cases for datapoint deletion

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
Shouldn't happen but somehow there is a question with a null text field
Prevent crashes in the reports for null question titles
NA
=> [#3773] prevent crash when question text is missing

GAE/src/org/waterforpeople/mapping/app/web/SurveyAssemblyServlet.java
use appId from config if exists
=> [#3778] use xmlAppId from config

GAE/test/org/akvo/flow/api/app/DataStoreTestUtil.java, GAE/test/org/akvo/flow/rest/handler/FormInstanceRequestHandlerTests.java
=> [#3597] Add tests for deletion of monitoriong forms

Dashboard/app/js/templates/navSurveys/question-view.handlebars
=> [#3793] Fix translation placeholders formatting

GAE/src/com/gallatinsystems/survey/dao/QuestionDao.java, GAE/src/org/waterforpeople/mapping/app/web/rest/QuestionRestService.java
Reverts akvo/akvo-flow#3797
Realized this is not going to work as we need all possible combination of cases
=> Revert "[#3796] optimize variable name verification"

GAE/src/org/waterforpeople/mapping/app/web/SurveyAssemblyServlet.java
=> [#3805] improve logging of errors

GAE/src/org/waterforpeople/mapping/app/web/SurveyAssemblyServlet.java
publish survey silently fails no message, no logs
add a message also when the xml generation fails + cleanup and remove some logs
=> [#3805] add message for publish failure

ci/flip-production-traffic.sh, ci/promote-test-to-prod.sh, notify.team.sh
=> [#3812] Upgrate flow deployment docker containers

GAE/src/org/akvo/flow/util/OneTimePadCypher.java
=> [#3819] use url decoder to prevent encoding errors

Dashboard/app/js/templates/navData/data-subnav.handlebars, GAE/src/org/waterforpeople/mapping/app/web/EnvServlet.java, GAE/war/Env.vm
=> [#3791] Add bulk image upload feature flag

GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java
=> [#3791] Remove broken logging statement

GAE/src/org/waterforpeople/mapping/app/web/EnvServlet.java
=> [#3791] Fix broken property

GAE/pom.xml
=> [#3849] Add logging library along with bridge to log both log4j and java util logging

Dashboard/app/js/lib/controllers/survey-controllers.js, GAE/src/org/waterforpeople/mapping/app/web/EnvServlet.java, GAE/war/Env.vm
* Form publishing now based on a JSON payload sent from the client side
* Added a feature flag for this functionality. ]
=> [#3833] Assemble the form to be published on the client side

Dashboard/app/js/lib/controllers/survey-controllers.js
=> [#3833] Update the form data at the client when publishing succeeds

GAE/src/org/akvo/flow/rest/ImageUploadRestService.java, GAE/test/org/akvo/flow/rest/ImageUploadRestServiceTest.java
Errors not handled properly for image upload
Actually throw exceptions instead of a response code
=> [#3843] handle errors for image upload properly

Dashboard/app/css/main.scss, Dashboard/app/dashboard.ejs, Dashboard/app/js/lib/controllers/permissions.js, Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/templates/application/application.handlebars
=> [#3833] Display status icons when publishing forms

Dashboard/app/js/lib/views/surveys/form-share.jsx, Dashboard/app/js/lib/views/surveys/form-view.js
=> [#3833] Prevent dashboard errors when showing publishing status

GAE/src/org/akvo/flow/rest/handler/FormInstanceRequestHandler.java, GAE/test/org/akvo/flow/rest/handler/FormInstanceRequestHandlerTests.java
=> [#3860] Deletion of orphaned form instances

GAE/src/org/akvo/flow/rest/handler/FormInstanceRequestHandler.java
=> [#3860] Log situations where an orphansed form instance is deleted

Dashboard/app/js/lib/controllers/survey-controllers.js
=> [#3795] Ensure OK button is showing on old publish dialog

GAE/src/com/gallatinsystems/framework/dao/BaseDAO.java
=> [#3865] Use ordered set to create object keys and remove duplicates

Dashboard/app/js/lib/controllers/languages.js
=> [#3867] Add Bemba to list of languages on dashboard

Dashboard/app/js/templates/navSurveys/form.handlebars, GAE/src/org/waterforpeople/mapping/app/web/EnvServlet.java, GAE/war/Env.vm
#3874 Display Form instance API URL Feature Flag
Added `showFormInstanceApiUrl` properties to `flowenv.js`
=> [#3874, #3871] Add Display Form Instance API feature flag

Dashboard/app/js/templates/application/footer.handlebars
=> Modified the year on the copyright

Dashboard/app/css/main.scss
There was a scroll on each survey panel.
Removed overflow: auto
=> Scroll bar in survey display area

Dashboard/app/js/templates/application/footer-public.handlebars
=> Modified copyright year

Dashboard/app/js/lib/components/forms/form-share/index.jsx, Dashboard/app/js/lib/components/forms/form-share/style.scss, Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/lib/models/models.js, Dashboard/app/js/lib/views/surveys/form-share.jsx, GAE/pom.xml, GAE/src/com/gallatinsystems/survey/domain/Survey.java, GAE/src/com/gallatinsystems/survey/domain/WebForm.java, GAE/src/org/akvo/flow/rest/form/FormAssemblyRestService.java, GAE/src/org/akvo/flow/rest/form/FormMapper.java, GAE/src/org/akvo/flow/xml/XmlForm.java, GAE/src/org/waterforpeople/mapping/app/gwt/client/survey/SurveyDto.java, GAE/src/org/waterforpeople/mapping/app/web/EnvServlet.java, GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyRestService.java, GAE/test/org/akvo/flow/xml/FlowXmlObjectWriterTests.java, GAE/war/Env.vm, docker-compose.yml
* Note that you need to ensure that the webform v2 feature flag is enabled.
Instance with webform v2 enabled.
Default password in survey XML
=> [#3917] Webforms v2 link in UI + default password

GAE/war/WEB-INF/datastore-indexes.xml
=> [#3932] Add QuestionAnswerStore datastore-index

ci/flip-production-traffic.sh, ci/promote-test-to-prod.sh
=> [#3937] Update docker image version on promote and flip scripts

Dashboard/app/js/lib/controllers/data-controllers.js, Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/lib/models/FLOWrest-adapter-v2-common.js, Dashboard/app/js/lib/router/router.js
Send initial data load requests sequentially, not parallel.
=> Adjust Surveys page initial data loading

GAE/src/org/akvo/flow/dao/DataPointAssignmentDao.java
---
- https://app.asana.com/0/0/1205713923487126
=> Fix datapoint assignment bug

Dashboard/app/js/lib/components/forms/form-share/index.jsx, Dashboard/app/js/lib/components/forms/form-share/style.scss, Dashboard/app/js/lib/components/reusable/Tooltip/index.jsx, Dashboard/app/js/lib/views/surveys/form-share.jsx, Dashboard/package-lock.json, Dashboard/package.json, GAE/src/locale/en.properties, GAE/src/locale/es.properties, GAE/src/locale/fr.properties, GAE/src/locale/id.properties, GAE/src/locale/pt.properties, GAE/src/locale/ui-strings.properties, GAE/src/locale/vi.properties, GAE/war/Env.vm
---
- https://app.asana.com/0/0/1204784502380663
=> Implement WebForm restriction

Dashboard/app/css/main.scss, Dashboard/app/js/lib/controllers/permissions.js, Dashboard/app/js/lib/controllers/reports-controllers.js, Dashboard/app/js/lib/tooltip.js, Dashboard/app/js/lib/views/reports/export-reports-views.js, Dashboard/app/js/templates/navReports/report.handlebars, Dashboard/app/js/templates/navReports/reports-list.handlebars, Dashboard/package.json, GAE/src/locale/en.properties, GAE/src/locale/es.properties, GAE/src/locale/fr.properties, GAE/src/locale/id.properties, GAE/src/locale/pt.properties, GAE/src/locale/ui-strings.properties, GAE/src/locale/vi.properties
---
- https://app.asana.com/0/0/1205687123250651
- https://app.asana.com/0/0/1204784502380659
=> Export restriction

Dashboard/app/dashboard.ejs, Dashboard/app/js/lib/controllers/survey-controllers.js, Dashboard/app/js/lib/views/surveys/survey-group-views.js, Dashboard/app/js/templates/navSurveys/project.handlebars, GAE/src/locale/en.properties, GAE/src/locale/es.properties, GAE/src/locale/fr.properties, GAE/src/locale/id.properties, GAE/src/locale/pt.properties, GAE/src/locale/ui-strings.properties, GAE/src/locale/vi.properties
---
- https://app.asana.com/0/0/1204784502380661
=> Multiple forms within survey restriction

Dashboard/app/css/main.scss, Dashboard/app/js/plugins/flowDashboard.js, GAE/src/org/akvo/flow/domain/FormSubmissionsLimit.java, GAE/src/org/akvo/flow/domain/UserFormSubmissionsCounter.java, GAE/src/org/akvo/flow/rest/CountFormSubmissionsRestService.java, GAE/src/org/waterforpeople/mapping/app/web/EnvServlet.java, GAE/src/org/waterforpeople/mapping/app/web/ProcessorServlet.java, GAE/test/org/akvo/flow/domain/UserFormSubmissionsCounterTest.java, GAE/test/org/akvo/flow/domain/UserFormSubmissionsCounterTestUtil.java, GAE/war/Env.vm, GAE/war/WEB-INF/rest-servlet.xml
---
- https://app.asana.com/0/0/1204784502380657
=> Form submissions restriction
